// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package anisdk

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const Layer = "core"
const Title = "KuberCloud ANI Core API"
const Version = "1.0.0"
const ServerURL = "https://{host}/api/v1"

var Operations = []string{
	"listQuotaMeta",
	"deleteTenantQuota",
	"getTenantQuota",
	"createTenantQuota",
	"updateTenantQuota",
	"upsertTenantQuota",
	"getTenantReservations",
	"putTenantReservations",
	"listAPIKeys",
	"createAPIKey",
	"revokeAPIKey",
	"logout",
	"beginOIDCLogin",
	"passwordLogin",
	"platformPasswordLogin",
	"postAuthRefresh",
	"completeOIDCLogin",
	"getBranding",
	"listStorageBuckets",
	"createStorageBucket",
	"setStorageBucketACL",
	"listStorageBucketLifecycleRules",
	"createStorageBucketLifecycleRule",
	"setStorageBucketLifecycleRules",
	"deleteStorageBucketLifecycleRule",
	"deleteBucketObject",
	"listBucketObjects",
	"generateBucketObjectPresignedURL",
	"uploadBucketObject",
	"createBucketPrefix",
	"setStorageBucketClass",
	"listEncryptionKeys",
	"createEncryptionKey",
	"deleteEncryptionKey",
	"getEncryptionKey",
	"revokeEncryptionKey",
	"rotateEncryptionKey",
	"sealEncryptionObject",
	"createEncryptionUnsealToken",
	"listStorageFilesystems",
	"createStorageFilesystem",
	"deleteStorageFilesystem",
	"getStorageFilesystem",
	"expandStorageFilesystem",
	"mountStorageFilesystem",
	"getFilesystemMountCommand",
	"listFilesystemMountTargets",
	"createFilesystemMountTarget",
	"unmountStorageFilesystem",
	"listGPUInventory",
	"getGPUOccupancy",
	"updateGPUDeviceStatus",
	"listGPUSchedulingQueues",
	"createGPUSchedulingQueue",
	"deleteGPUSchedulingQueue",
	"getGPUSchedulingQueue",
	"updateGPUSchedulingQueue",
	"listGPUSpecs",
	"createGPUSpec",
	"listGPUSpecAvailability",
	"deleteGPUSpec",
	"getGPUSpec",
	"liveness",
	"getInstanceOperation",
	"listInstances",
	"createInstance",
	"getInstance",
	"createInstanceConsoleSession",
	"listInstanceEvents",
	"createInstanceExecSession",
	"applyInstanceLifecycle",
	"listInstanceLogs",
	"getInstanceMetrics",
	"listInstanceOperations",
	"listSandboxCheckpoints",
	"createSandboxCheckpoint",
	"cloneSandboxCheckpoint",
	"restoreSandboxCheckpoint",
	"createSandboxCodeRun",
	"deleteSandboxFile",
	"listSandboxFiles",
	"writeSandboxFile",
	"createSandboxPort",
	"deleteSandboxPort",
	"createSandboxToken",
	"listInstanceSecurityEvents",
	"listK8sClusters",
	"createK8sCluster",
	"deleteK8sCluster",
	"getK8sCluster",
	"getK8sClusterKubeconfig",
	"listK8sClusterNodePools",
	"createK8sClusterNodePool",
	"deleteK8sClusterNodePool",
	"getK8sClusterNodePool",
	"updateK8sClusterNodePool",
	"proxyK8sClusterAPI",
	"upgradeK8sCluster",
	"listK8sClusterWorkloads",
	"reportTokenUsage",
	"getMeteringUsage",
	"getPlatformMeteringUsage",
	"listNetworkLoadBalancers",
	"createNetworkLoadBalancer",
	"deleteNetworkLoadBalancer",
	"getNetworkLoadBalancer",
	"getNetworkOverview",
	"listNetworkRoutes",
	"createNetworkRoute",
	"deleteNetworkRoute",
	"getNetworkRoute",
	"listNetworkSecurityGroups",
	"createNetworkSecurityGroup",
	"deleteNetworkSecurityGroup",
	"getNetworkSecurityGroup",
	"listNetworkSecurityGroupBindings",
	"createNetworkSecurityGroupBinding",
	"deleteNetworkSecurityGroupBinding",
	"listNetworkSecurityGroupRules",
	"createNetworkSecurityGroupRule",
	"deleteNetworkSecurityGroupRule",
	"getNetworkSecurityGroupRule",
	"updateNetworkSecurityGroupRule",
	"listNetworkSubnets",
	"createNetworkSubnet",
	"deleteNetworkSubnet",
	"getNetworkSubnet",
	"listNetworkSubnetIPAllocations",
	"listNetworkVPCs",
	"createNetworkVPC",
	"deleteNetworkVPC",
	"getNetworkVPC",
	"listEmailRecipients",
	"createEmailRecipient",
	"deleteEmailRecipient",
	"updateEmailRecipient",
	"getEmailSmtpConfig",
	"putEmailSmtpConfig",
	"listEmailSubscriptions",
	"putEmailSubscriptions",
	"sendTestEmail",
	"listStorageObjects",
	"createStorageObject",
	"uploadStorageObject",
	"deleteStorageObject",
	"getStorageObject",
	"downloadStorageObject",
	"listObservabilityAlertRules",
	"createObservabilityAlertRule",
	"deleteObservabilityAlertRule",
	"getObservabilityAlertRule",
	"updateObservabilityAlertRule",
	"queryObservability",
	"queryRangeObservability",
	"getPlatformWorkloadCapabilities",
	"createPlatformWorkload",
	"deletePlatformWorkload",
	"getPlatformWorkload",
	"updatePlatformWorkload",
	"applyPlatformWorkloadLifecycle",
	"getPlatformWorkloadLogs",
	"listQuotas",
	"getMyQuota",
	"readiness",
	"listRegistryImages",
	"getRegistryImageScanResult",
	"getRegistryOverview",
	"listRegistryProjects",
	"createRegistryProject",
	"createRegistryProjectPullSecret",
	"getRegistryProjectPushInstructions",
	"listRegistryRepositories",
	"listRegistryArtifacts",
	"setRegistryRepositoryPermission",
	"deleteRegistryRepositoryTag",
	"listRegistryRepositoryTagReferences",
	"getRegistryProjectScanReport",
	"getMyReservations",
	"listSandboxTemplates",
	"listSecrets",
	"createSecret",
	"deleteSecret",
	"getSecret",
	"bindSecret",
	"getTasksTaskId",
	"listVectorStores",
	"createVectorStore",
	"deleteVectorStore",
	"getVectorStore",
	"precheckVectorStoreDelete",
	"deleteVectorStoreDocuments",
	"insertVectorStoreDocuments",
	"deleteVectorStoreKnowledgeBaseLink",
	"setVectorStoreKnowledgeBaseLink",
	"rebuildVectorStoreIndex",
	"searchVectorStore",
	"listStorageVolumes",
	"createStorageVolume",
	"deleteStorageVolume",
	"getStorageVolume",
	"setVolumeAutoSnapshotPolicy",
	"expandStorageVolume",
	"mountStorageVolume",
	"completeVolumeOSInit",
	"getVolumeOSInitGuide",
	"listVolumeSnapshots",
	"createVolumeSnapshot",
	"createStorageVolumeFromSnapshot",
	"unmountStorageVolume",
}
var Paths = []string{
	"GET /admin/quota-meta",
	"DELETE /admin/tenants/{tenant_id}/quota",
	"GET /admin/tenants/{tenant_id}/quota",
	"POST /admin/tenants/{tenant_id}/quota",
	"PUT /admin/tenants/{tenant_id}/quota",
	"PUT /admin/tenants/{tenant_id}/quota/upsert",
	"GET /admin/tenants/{tenant_id}/reservations",
	"PUT /admin/tenants/{tenant_id}/reservations",
	"GET /auth/api-keys",
	"POST /auth/api-keys",
	"DELETE /auth/api-keys/{key_id}",
	"POST /auth/logout",
	"POST /auth/oidc/begin",
	"POST /auth/password/login",
	"POST /auth/platform/password/login",
	"POST /auth/refresh",
	"POST /auth/token",
	"GET /branding",
	"GET /buckets",
	"POST /buckets",
	"PUT /buckets/{bucket_id}/acl",
	"GET /buckets/{bucket_id}/lifecycle-rules",
	"POST /buckets/{bucket_id}/lifecycle-rules",
	"PUT /buckets/{bucket_id}/lifecycle-rules",
	"DELETE /buckets/{bucket_id}/lifecycle-rules/{rule_id}",
	"DELETE /buckets/{bucket_id}/objects",
	"GET /buckets/{bucket_id}/objects",
	"POST /buckets/{bucket_id}/objects/presigned-url",
	"POST /buckets/{bucket_id}/objects/upload",
	"POST /buckets/{bucket_id}/prefixes",
	"PUT /buckets/{bucket_id}/storage-class",
	"GET /encryption/keys",
	"POST /encryption/keys",
	"DELETE /encryption/keys/{key_id}",
	"GET /encryption/keys/{key_id}",
	"POST /encryption/keys/{key_id}/revoke",
	"POST /encryption/keys/{key_id}/rotate",
	"POST /encryption/seal",
	"POST /encryption/unseal-token",
	"GET /filesystems",
	"POST /filesystems",
	"DELETE /filesystems/{filesystem_id}",
	"GET /filesystems/{filesystem_id}",
	"POST /filesystems/{filesystem_id}/expand",
	"POST /filesystems/{filesystem_id}/mount",
	"GET /filesystems/{filesystem_id}/mount-command",
	"GET /filesystems/{filesystem_id}/mount-targets",
	"POST /filesystems/{filesystem_id}/mount-targets",
	"POST /filesystems/{filesystem_id}/unmount",
	"GET /gpu-inventory",
	"GET /gpu-inventory/occupancy",
	"PATCH /gpu-inventory/{device_id}",
	"GET /gpu-scheduling/queues",
	"POST /gpu-scheduling/queues",
	"DELETE /gpu-scheduling/queues/{queue_id}",
	"GET /gpu-scheduling/queues/{queue_id}",
	"PATCH /gpu-scheduling/queues/{queue_id}",
	"GET /gpu-specs",
	"POST /gpu-specs",
	"GET /gpu-specs/availability",
	"DELETE /gpu-specs/{spec_id}",
	"GET /gpu-specs/{spec_id}",
	"GET /healthz",
	"GET /instance-operations/{operation_id}",
	"GET /instances",
	"POST /instances",
	"GET /instances/{instance_id}",
	"POST /instances/{instance_id}/console",
	"GET /instances/{instance_id}/events",
	"POST /instances/{instance_id}/exec",
	"POST /instances/{instance_id}/lifecycle",
	"GET /instances/{instance_id}/logs",
	"GET /instances/{instance_id}/metrics",
	"GET /instances/{instance_id}/operations",
	"GET /instances/{instance_id}/sandbox/checkpoints",
	"POST /instances/{instance_id}/sandbox/checkpoints",
	"POST /instances/{instance_id}/sandbox/checkpoints/{checkpoint_id}/clone",
	"POST /instances/{instance_id}/sandbox/checkpoints/{checkpoint_id}/restore",
	"POST /instances/{instance_id}/sandbox/code-runs",
	"DELETE /instances/{instance_id}/sandbox/files",
	"GET /instances/{instance_id}/sandbox/files",
	"POST /instances/{instance_id}/sandbox/files",
	"POST /instances/{instance_id}/sandbox/ports",
	"DELETE /instances/{instance_id}/sandbox/ports/{port}",
	"POST /instances/{instance_id}/sandbox/tokens",
	"GET /instances/{instance_id}/security-events",
	"GET /k8s-clusters",
	"POST /k8s-clusters",
	"DELETE /k8s-clusters/{cluster_id}",
	"GET /k8s-clusters/{cluster_id}",
	"GET /k8s-clusters/{cluster_id}/kubeconfig",
	"GET /k8s-clusters/{cluster_id}/node-pools",
	"POST /k8s-clusters/{cluster_id}/node-pools",
	"DELETE /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
	"GET /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
	"PATCH /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
	"POST /k8s-clusters/{cluster_id}/proxy",
	"POST /k8s-clusters/{cluster_id}/upgrade",
	"GET /k8s-clusters/{cluster_id}/workloads",
	"POST /metering/token-usage",
	"GET /metering/usage",
	"GET /metering/usage/platform",
	"GET /networks/load-balancers",
	"POST /networks/load-balancers",
	"DELETE /networks/load-balancers/{load_balancer_id}",
	"GET /networks/load-balancers/{load_balancer_id}",
	"GET /networks/overview",
	"GET /networks/routes",
	"POST /networks/routes",
	"DELETE /networks/routes/{route_id}",
	"GET /networks/routes/{route_id}",
	"GET /networks/security-groups",
	"POST /networks/security-groups",
	"DELETE /networks/security-groups/{security_group_id}",
	"GET /networks/security-groups/{security_group_id}",
	"GET /networks/security-groups/{security_group_id}/bindings",
	"POST /networks/security-groups/{security_group_id}/bindings",
	"DELETE /networks/security-groups/{security_group_id}/bindings/{binding_id}",
	"GET /networks/security-groups/{security_group_id}/rules",
	"POST /networks/security-groups/{security_group_id}/rules",
	"DELETE /networks/security-groups/{security_group_id}/rules/{rule_id}",
	"GET /networks/security-groups/{security_group_id}/rules/{rule_id}",
	"PUT /networks/security-groups/{security_group_id}/rules/{rule_id}",
	"GET /networks/subnets",
	"POST /networks/subnets",
	"DELETE /networks/subnets/{subnet_id}",
	"GET /networks/subnets/{subnet_id}",
	"GET /networks/subnets/{subnet_id}/ip-allocations",
	"GET /networks/vpcs",
	"POST /networks/vpcs",
	"DELETE /networks/vpcs/{vpc_id}",
	"GET /networks/vpcs/{vpc_id}",
	"GET /notifications/email/recipients",
	"POST /notifications/email/recipients",
	"DELETE /notifications/email/recipients/{recipient_id}",
	"PATCH /notifications/email/recipients/{recipient_id}",
	"GET /notifications/email/smtp",
	"PUT /notifications/email/smtp",
	"GET /notifications/email/subscriptions",
	"PUT /notifications/email/subscriptions",
	"POST /notifications/email/test",
	"GET /objects",
	"POST /objects",
	"POST /objects/upload",
	"DELETE /objects/{object_id}",
	"GET /objects/{object_id}",
	"GET /objects/{object_id}/download",
	"GET /observability/alert-rules",
	"POST /observability/alert-rules",
	"DELETE /observability/alert-rules/{rule_id}",
	"GET /observability/alert-rules/{rule_id}",
	"PATCH /observability/alert-rules/{rule_id}",
	"GET /observability/query",
	"GET /observability/query_range",
	"GET /platform-workload-capabilities",
	"POST /platform-workloads",
	"DELETE /platform-workloads/{workload_id}",
	"GET /platform-workloads/{workload_id}",
	"PATCH /platform-workloads/{workload_id}",
	"POST /platform-workloads/{workload_id}/lifecycle",
	"GET /platform-workloads/{workload_id}/logs",
	"GET /quotas",
	"GET /quotas/me",
	"GET /readyz",
	"GET /registry/images",
	"GET /registry/images/scan-result",
	"GET /registry/overview",
	"GET /registry/projects",
	"POST /registry/projects",
	"POST /registry/projects/{project}/pull-secret",
	"GET /registry/projects/{project}/push-instructions",
	"GET /registry/projects/{project}/repositories",
	"GET /registry/projects/{project}/repositories/{repository}/artifacts",
	"POST /registry/projects/{project}/repositories/{repository}/permissions",
	"DELETE /registry/projects/{project}/repositories/{repository}/tags/{tag}",
	"GET /registry/projects/{project}/repositories/{repository}/tags/{tag}/references",
	"GET /registry/projects/{project}/scan-report",
	"GET /reservations/me",
	"GET /sandbox-templates",
	"GET /secrets",
	"POST /secrets",
	"DELETE /secrets/{secret_id}",
	"GET /secrets/{secret_id}",
	"POST /secrets/{secret_id}/bindings",
	"GET /tasks/{task_id}",
	"GET /vector-stores",
	"POST /vector-stores",
	"DELETE /vector-stores/{vector_store_id}",
	"GET /vector-stores/{vector_store_id}",
	"GET /vector-stores/{vector_store_id}/delete-precheck",
	"DELETE /vector-stores/{vector_store_id}/documents",
	"POST /vector-stores/{vector_store_id}/documents",
	"DELETE /vector-stores/{vector_store_id}/knowledge-base-link",
	"PUT /vector-stores/{vector_store_id}/knowledge-base-link",
	"POST /vector-stores/{vector_store_id}/rebuild-index",
	"POST /vector-stores/{vector_store_id}/search",
	"GET /volumes",
	"POST /volumes",
	"DELETE /volumes/{volume_id}",
	"GET /volumes/{volume_id}",
	"PUT /volumes/{volume_id}/auto-snapshot-policy",
	"POST /volumes/{volume_id}/expand",
	"POST /volumes/{volume_id}/mount",
	"POST /volumes/{volume_id}/os-init-complete",
	"GET /volumes/{volume_id}/os-init-guide",
	"GET /volumes/{volume_id}/snapshots",
	"POST /volumes/{volume_id}/snapshots",
	"POST /volumes/{volume_id}/snapshots/{snapshot_id}/create-volume",
	"POST /volumes/{volume_id}/unmount",
}
var Schemas = []string{
	"APIKeyInfo",
	"AsyncTask",
	"BeginOIDCLoginRequest",
	"BeginOIDCLoginResponse",
	"BucketObjectDeleteResponse",
	"BucketObjectPresignedURLRequest",
	"BucketObjectUploadRequest",
	"BucketPrefixCreateRequest",
	"CloneSandboxCheckpointRequest",
	"CompleteOIDCLoginRequest",
	"CoreDevProfileInfo",
	"CreateAPIKeyRequest",
	"CreateAPIKeyResponse",
	"CreateContainerInstanceConfig",
	"CreateEmailRecipientRequest",
	"CreateGPUContainerInstanceConfig",
	"CreateInstanceConsoleSessionRequest",
	"CreateInstanceExecSessionRequest",
	"CreateInstanceRequest",
	"CreateInstanceResponse",
	"CreateNetworkLoadBalancerRequest",
	"CreateNetworkRouteRequest",
	"CreateNetworkSecurityGroupBindingRequest",
	"CreateNetworkSecurityGroupRequest",
	"CreateNetworkSecurityGroupRuleRequest",
	"CreateNetworkSubnetRequest",
	"CreateNetworkVPCRequest",
	"CreateObservabilityAlertRuleRequest",
	"CreateRegistryProjectRequest",
	"CreateRegistryPullSecretRequest",
	"CreateSandboxCheckpointRequest",
	"CreateSandboxCodeRunRequest",
	"CreateSandboxPortRequest",
	"CreateSandboxTokenRequest",
	"CreateStorageBucketRequest",
	"CreateStorageFilesystemRequest",
	"CreateStorageObjectRequest",
	"CreateStorageVolumeFromSnapshotRequest",
	"CreateStorageVolumeRequest",
	"CreateVMInstanceConfig",
	"CreateVectorStoreRequest",
	"CreateVolumeSnapshotRequest",
	"CursorPage",
	"EmailRecipient",
	"EmailRecipientListResponse",
	"EmailSmtpConfigResponse",
	"EmailSubscription",
	"EmailSubscriptionListResponse",
	"EncryptionKey",
	"EncryptionKeyCreateRequest",
	"EncryptionKeyListResponse",
	"EncryptionKeyRevokeRequest",
	"EncryptionKeyRotateRequest",
	"EncryptionKeyRotationResponse",
	"EncryptionSealRequest",
	"EncryptionSealResponse",
	"EncryptionUnsealTokenRequest",
	"EncryptionUnsealTokenResponse",
	"ErrorResponse",
	"FilesystemAttachment",
	"FilesystemMountCommand",
	"FilesystemMountTarget",
	"FilesystemMountTargetCreateRequest",
	"FilesystemMountTargetListResponse",
	"GPUDeviceStatusUpdateRequest",
	"GPUInventoryListResponse",
	"GPUInventoryRecord",
	"GPUOccupancyStats",
	"GPUSchedulingQueue",
	"GPUSchedulingQueueCreateRequest",
	"GPUSchedulingQueueListResponse",
	"GPUSchedulingQueueUpdateRequest",
	"GPUSpec",
	"GPUSpecAvailability",
	"GPUSpecAvailabilityListResponse",
	"GPUSpecCreateRequest",
	"GPUSpecListResponse",
	"GPUSpecNodeAffinity",
	"GPUSpecSummary",
	"GPUSpecVolcanoResources",
	"HealthCheck",
	"InstanceAccessSummary",
	"InstanceComputeSummary",
	"InstanceConsoleSession",
	"InstanceDiskSpec",
	"InstanceEnvVar",
	"InstanceEvent",
	"InstanceEventListResponse",
	"InstanceExecSession",
	"InstanceFilesystemMount",
	"InstanceImageSummary",
	"InstanceLifecycleRequest",
	"InstanceLifecycleResponse",
	"InstanceListResponse",
	"InstanceLogEntry",
	"InstanceLogListResponse",
	"InstanceMetrics",
	"InstanceNetworkConfig",
	"InstanceNetworkSummary",
	"InstanceOperation",
	"InstancePortSpec",
	"InstanceRecord",
	"InstanceSecurityEvent",
	"InstanceSecurityEventListResponse",
	"InstanceStorageAttachment",
	"InstanceVolumeMount",
	"InstanceWorkloadIdentityConfig",
	"K8sCluster",
	"K8sClusterCreateRequest",
	"K8sClusterKubeconfig",
	"K8sClusterListResponse",
	"K8sClusterNodePool",
	"K8sClusterNodePoolCreateRequest",
	"K8sClusterNodePoolGPU",
	"K8sClusterNodePoolListResponse",
	"K8sClusterNodePoolUpdateRequest",
	"K8sClusterProxyRequest",
	"K8sClusterProxyResponse",
	"K8sClusterUpgradeRequest",
	"K8sClusterWorkload",
	"K8sClusterWorkloadListResponse",
	"ListAPIKeysResponse",
	"LogoutRequest",
	"MeteringUsageRecord",
	"MeteringUsageResponse",
	"NetworkLoadBalancer",
	"NetworkLoadBalancerListResponse",
	"NetworkLoadBalancerListener",
	"NetworkOverview",
	"NetworkOverviewCapability",
	"NetworkOverviewDeleteRisk",
	"NetworkOverviewRelationship",
	"NetworkOverviewResourceKind",
	"NetworkOverviewResourceSummary",
	"NetworkResourceState",
	"NetworkRoute",
	"NetworkRouteListResponse",
	"NetworkSecurityGroup",
	"NetworkSecurityGroupBinding",
	"NetworkSecurityGroupBindingListResponse",
	"NetworkSecurityGroupBindingTargetType",
	"NetworkSecurityGroupListResponse",
	"NetworkSecurityGroupRule",
	"NetworkSecurityGroupRuleListResponse",
	"NetworkSecurityGroupRuleResource",
	"NetworkSubnet",
	"NetworkSubnetIPAllocation",
	"NetworkSubnetIPAllocationListResponse",
	"NetworkSubnetListResponse",
	"NetworkVPC",
	"NetworkVPCListResponse",
	"ObservabilityAlertRule",
	"ObservabilityAlertRuleListResponse",
	"ObservabilityQueryResponse",
	"ObservabilityRangeQueryResponse",
	"PasswordLoginRequest",
	"PlatformPasswordLoginRequest",
	"PlatformWorkload",
	"PlatformWorkloadAcceleratorCapability",
	"PlatformWorkloadAcceleratorResources",
	"PlatformWorkloadArtifact",
	"PlatformWorkloadCapabilities",
	"PlatformWorkloadCreateRequest",
	"PlatformWorkloadHealthCheck",
	"PlatformWorkloadLifecycleRequest",
	"PlatformWorkloadLogEntry",
	"PlatformWorkloadLogListResponse",
	"PlatformWorkloadMetadata",
	"PlatformWorkloadNetwork",
	"PlatformWorkloadPort",
	"PlatformWorkloadResources",
	"PlatformWorkloadRole",
	"PlatformWorkloadScheduling",
	"PlatformWorkloadSecretBinding",
	"PlatformWorkloadTopology",
	"PlatformWorkloadUpdateRequest",
	"PutEmailSmtpConfigRequest",
	"PutEmailSubscriptionsRequest",
	"Quota",
	"QuotaCreateItem",
	"QuotaCreateRequest",
	"QuotaDeleteResponse",
	"QuotaItem",
	"QuotaListResult",
	"QuotaMeta",
	"QuotaMetaListResponse",
	"QuotaUpdateItem",
	"QuotaUpdateRequest",
	"QuotaUpsertItem",
	"QuotaUpsertRequest",
	"RefreshAccessTokenRequest",
	"RefreshAccessTokenResponse",
	"RegistryArtifact",
	"RegistryArtifactListResponse",
	"RegistryCommand",
	"RegistryDeletedTag",
	"RegistryImage",
	"RegistryImageListResponse",
	"RegistryImageReference",
	"RegistryImageReferenceListResponse",
	"RegistryOverview",
	"RegistryOverviewCapability",
	"RegistryOverviewDeleteRisk",
	"RegistryOverviewQuickAction",
	"RegistryOverviewRelationship",
	"RegistryOverviewResourceSummary",
	"RegistryOverviewVulnerabilitySummary",
	"RegistryPermission",
	"RegistryProject",
	"RegistryProjectListResponse",
	"RegistryProjectScanReport",
	"RegistryPullSecret",
	"RegistryPushInstructions",
	"RegistryRepository",
	"RegistryRepositoryListResponse",
	"RegistryScanResult",
	"ReportTokenUsageRequest",
	"ReservationPutRequest",
	"ReservationView",
	"RevokeStatusResponse",
	"SandboxCheckpoint",
	"SandboxCheckpointActionRequest",
	"SandboxCheckpointListResponse",
	"SandboxCodeRun",
	"SandboxConfig",
	"SandboxFile",
	"SandboxFileListResponse",
	"SandboxInstanceStatus",
	"SandboxNetworkEgressPolicy",
	"SandboxPort",
	"SandboxTemplate",
	"SandboxTemplateListResponse",
	"SandboxTokenResponse",
	"Secret",
	"SecretBinding",
	"SecretBindingRequest",
	"SecretCreateRequest",
	"SecretListResponse",
	"SendTestEmailResponse",
	"SetRegistryPermissionRequest",
	"StorageBucketACLUpdateRequest",
	"StorageBucketClassUpdateRequest",
	"StorageBucketLifecycleRule",
	"StorageBucketLifecycleRuleCreateRequest",
	"StorageBucketLifecycleRuleListResponse",
	"StorageBucketLifecycleRulesUpdateRequest",
	"StorageBucketListResponse",
	"StorageBucketObjectEntry",
	"StorageBucketObjectListResponse",
	"StorageBucketRecord",
	"StorageFilesystem",
	"StorageFilesystemExpandRequest",
	"StorageFilesystemListResponse",
	"StorageFilesystemMountRequest",
	"StorageFilesystemUnmountRequest",
	"StorageObject",
	"StorageObjectDownloadInfo",
	"StorageObjectListResponse",
	"StorageObjectUploadRequest",
	"StorageObjectUploadResponse",
	"StorageResourceState",
	"StorageVolume",
	"StorageVolumeAutoSnapshotPolicy",
	"StorageVolumeAutoSnapshotPolicyUpdateRequest",
	"StorageVolumeExpandRequest",
	"StorageVolumeListResponse",
	"StorageVolumeMountHistoryEntry",
	"StorageVolumeMountRequest",
	"StorageVolumeUnmountRequest",
	"TokenPairResponse",
	"TokenUsageReport",
	"UpdateEmailRecipientRequest",
	"UpdateNetworkSecurityGroupRuleRequest",
	"UpdateObservabilityAlertRuleRequest",
	"VectorStore",
	"VectorStoreDeletePrecheck",
	"VectorStoreDocumentDeleteResponse",
	"VectorStoreDocumentInsertRequest",
	"VectorStoreDocumentInsertResponse",
	"VectorStoreIndexStatus",
	"VectorStoreKnowledgeBaseLinkRequest",
	"VectorStoreKnowledgeBaseRef",
	"VectorStoreListResponse",
	"VectorStoreSearchHit",
	"VectorStoreSearchRequest",
	"VectorStoreSearchResponse",
	"VectorStoreState",
	"VolumeOSInitCompleteRequest",
	"VolumeOSInitGuide",
	"VolumeSnapshotListResponse",
	"VolumeSnapshotRecord",
	"WorkloadIdentityBinding",
	"WriteSandboxFileRequest",
}
var IdempotencyOperations = []string{
	"createStorageBucket",
	"setStorageBucketACL",
	"createStorageBucketLifecycleRule",
	"setStorageBucketLifecycleRules",
	"uploadBucketObject",
	"createBucketPrefix",
	"setStorageBucketClass",
	"createEncryptionKey",
	"revokeEncryptionKey",
	"rotateEncryptionKey",
	"sealEncryptionObject",
	"createStorageFilesystem",
	"expandStorageFilesystem",
	"mountStorageFilesystem",
	"createFilesystemMountTarget",
	"unmountStorageFilesystem",
	"createInstance",
	"createInstanceExecSession",
	"applyInstanceLifecycle",
	"createSandboxCheckpoint",
	"cloneSandboxCheckpoint",
	"restoreSandboxCheckpoint",
	"createSandboxCodeRun",
	"writeSandboxFile",
	"createSandboxPort",
	"createSandboxToken",
	"createK8sCluster",
	"createK8sClusterNodePool",
	"updateK8sClusterNodePool",
	"proxyK8sClusterAPI",
	"upgradeK8sCluster",
	"reportTokenUsage",
	"createNetworkLoadBalancer",
	"createNetworkRoute",
	"createNetworkSecurityGroup",
	"createNetworkSecurityGroupBinding",
	"createNetworkSecurityGroupRule",
	"createNetworkSubnet",
	"createNetworkVPC",
	"createStorageObject",
	"uploadStorageObject",
	"createObservabilityAlertRule",
	"updateObservabilityAlertRule",
	"createPlatformWorkload",
	"updatePlatformWorkload",
	"applyPlatformWorkloadLifecycle",
	"createRegistryProject",
	"createRegistryProjectPullSecret",
	"setRegistryRepositoryPermission",
	"createSecret",
	"createVectorStore",
	"insertVectorStoreDocuments",
	"setVectorStoreKnowledgeBaseLink",
	"createStorageVolume",
	"setVolumeAutoSnapshotPolicy",
	"expandStorageVolume",
	"mountStorageVolume",
	"completeVolumeOSInit",
	"createVolumeSnapshot",
	"createStorageVolumeFromSnapshot",
	"unmountStorageVolume",
}
var CursorPaginationOperations = []string{
	"listStorageBuckets",
	"listBucketObjects",
	"listEncryptionKeys",
	"listStorageFilesystems",
	"listFilesystemMountTargets",
	"listGPUInventory",
	"listGPUSpecs",
	"listInstances",
	"listInstanceEvents",
	"listInstanceLogs",
	"listInstanceOperations",
	"listSandboxCheckpoints",
	"listSandboxFiles",
	"listInstanceSecurityEvents",
	"listK8sClusters",
	"listK8sClusterWorkloads",
	"listNetworkLoadBalancers",
	"listNetworkRoutes",
	"listNetworkSecurityGroups",
	"listNetworkSecurityGroupBindings",
	"listNetworkSecurityGroupRules",
	"listNetworkSubnets",
	"listNetworkSubnetIPAllocations",
	"listNetworkVPCs",
	"listStorageObjects",
	"listObservabilityAlertRules",
	"getPlatformWorkloadLogs",
	"listQuotas",
	"listRegistryImages",
	"listRegistryProjects",
	"listRegistryRepositories",
	"listRegistryArtifacts",
	"listSandboxTemplates",
	"listSecrets",
	"listVectorStores",
	"listStorageVolumes",
	"listVolumeSnapshots",
}
var ErrorCodes = []string{
	"BAD_REQUEST",
	"CONFLICT",
	"DEVICE_NOT_FOUND",
	"FORBIDDEN",
	"GPU_SPEC_CONFLICT",
	"GPU_SPEC_IN_USE",
	"GPU_SPEC_NOT_FOUND",
	"GPU_TYPE_NOT_IN_NODES",
	"INTERNAL_ERROR",
	"INVALID_FILTER",
	"NOT_FOUND",
	"NOT_IMPLEMENTED",
	"PRECONDITION_FAILED",
	"QUOTA_ALREADY_EXISTS",
	"QUOTA_EXCEEDED",
	"QUOTA_NOT_FOUND",
	"QUOTA_RESOURCE_NOT_REGISTERED",
	"QUOTA_UPDATE_UNCERTAIN",
	"RATE_LIMIT_EXCEEDED",
	"RESERVATION_EXCEEDS_QUOTA",
	"RESERVED_INSUFFICIENT",
	"TENANT_NOT_FOUND",
	"UNAUTHORIZED",
	"UNAVAILABLE",
	"VALIDATION_FAILED",
	"VECTOR_STORE_NOT_FOUND",
}

type APIError struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id"`
	Details   map[string]any `json:"details,omitempty"`
}

func (err APIError) Error() string {
	if err.Message == "" {
		return err.Code
	}
	if err.Code == "" {
		return err.Message
	}
	return err.Code + ": " + err.Message
}

type Client struct {
	BaseURL string
	Token   string
}

type RequestOptions struct {
	Body    map[string]any
	Params  map[string]string
	Headers map[string]string
}

func NewClient(baseURL string, token string) Client {
	if baseURL == "" {
		baseURL = ServerURL
	}
	return Client{BaseURL: baseURL, Token: token}
}

func (client Client) Request(method string, path string, options RequestOptions) (any, error) {
	requestURL, err := client.requestURL(path, options.Params)
	if err != nil {
		return nil, err
	}
	var body io.Reader
	if options.Body != nil {
		payload, err := json.Marshal(options.Body)
		if err != nil {
			return nil, fmt.Errorf("encode request body: %w", err)
		}
		body = bytes.NewReader(payload)
	}
	req, err := http.NewRequest(strings.ToUpper(method), requestURL, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if client.Token != "" {
		req.Header.Set("Authorization", "Bearer "+client.Token)
	}
	for key, value := range options.Headers {
		req.Header.Set(key, value)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	return decodeResponse(resp)
}

func (client Client) requestURL(path string, params map[string]string) (string, error) {
	base := strings.TrimRight(client.BaseURL, "/")
	relative := "/" + strings.TrimLeft(path, "/")
	parsed, err := url.Parse(base + relative)
	if err != nil {
		return "", err
	}
	query := parsed.Query()
	for key, value := range params {
		if value != "" {
			query.Set(key, value)
		}
	}
	parsed.RawQuery = query.Encode()
	return parsed.String(), nil
}

func decodeResponse(resp *http.Response) (any, error) {
	if resp.StatusCode == http.StatusNoContent {
		return nil, nil
	}
	payload, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if len(payload) == 0 {
		if resp.StatusCode >= 400 {
			return nil, fmt.Errorf("ANI API request failed: %d", resp.StatusCode)
		}
		return nil, nil
	}
	var decoded any
	if strings.Contains(resp.Header.Get("Content-Type"), "application/json") {
		if err := json.Unmarshal(payload, &decoded); err != nil {
			return nil, err
		}
	} else {
		decoded = string(payload)
	}
	if resp.StatusCode >= 400 {
		if data, ok := decoded.(map[string]any); ok {
			code, _ := data["code"].(string)
			message, _ := data["message"].(string)
			requestID, _ := data["request_id"].(string)
			details, _ := data["details"].(map[string]any)
			if code != "" && message != "" {
				return nil, APIError{Code: code, Message: message, RequestID: requestID, Details: details}
			}
		}
		return nil, fmt.Errorf("ANI API request failed: %d", resp.StatusCode)
	}
	return decoded, nil
}

func HasOperation(operationID string) bool {
	for _, operation := range Operations {
		if operation == operationID {
			return true
		}
	}
	return false
}

func NewIdempotencyKey(prefix string) (string, error) {
	if prefix == "" {
		prefix = "ani"
	}
	random := make([]byte, 16)
	if _, err := rand.Read(random); err != nil {
		return "", fmt.Errorf("generate idempotency key: %w", err)
	}
	return prefix + "_" + hex.EncodeToString(random), nil
}

func WithIdempotencyKey(body map[string]any, key string) (map[string]any, error) {
	if body == nil {
		body = map[string]any{}
	}
	if key == "" {
		generated, err := NewIdempotencyKey("ani")
		if err != nil {
			return nil, err
		}
		key = generated
	}
	body["idempotency_key"] = key
	return body, nil
}

func CursorParams(limit int, cursor string) map[string]string {
	params := map[string]string{}
	if limit > 0 {
		params["limit"] = fmt.Sprintf("%d", limit)
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	return params
}

func IsAPIErrorCode(code string) bool {
	for _, item := range ErrorCodes {
		if item == code {
			return true
		}
	}
	return false
}

func NewAPIError(code string, message string, requestID string, details map[string]any) APIError {
	return APIError{Code: code, Message: message, RequestID: requestID, Details: details}
}
