// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
export const layer = "services" as const;
export const title = "KuberCloud ANI Services API" as const;
export const version = "1.0.0" as const;
export const serverURL = "https://{host}/api/v1/svc" as const;
export const operations = [
  "listGpuContainers",
  "createGpuContainer",
  "listAvailableGpus",
  "deleteGpuContainer",
  "getGpuContainer",
  "patchGpuContainer",
  "getGpuContainerMetrics",
  "rebuildGpuContainer",
  "rollbackGpuContainer",
  "listGpuContainerVersions",
  "getInferenceOperation",
  "listInferenceServices",
  "createInferenceService",
  "deleteInferenceService",
  "getInferenceService",
  "updateInferenceService",
  "applyInferenceServiceLifecycle",
  "getInferenceServiceLogs",
  "updateInferenceServicePolicies",
  "testInferenceService",
  "listIntegrations",
  "createIntegration",
  "createIntegrationBot",
  "listKnowledgeBases",
  "createKnowledgeBase",
  "deleteKnowledgeBase",
  "getKnowledgeBase",
  "listKnowledgeBaseCitations",
  "getKnowledgeBaseConfig",
  "updateKnowledgeBaseConfig",
  "listKnowledgeBaseDocuments",
  "getDocumentUploadURL",
  "deleteKnowledgeBaseDocument",
  "notifyDocumentUploaded",
  "reparseKnowledgeBaseDocument",
  "listKnowledgeBaseModels",
  "updateKnowledgeBasePermissions",
  "queryKnowledgeBase",
  "streamQueryKnowledgeBase",
  "rebuildKnowledgeBase",
  "listKnowledgeBaseSessions",
  "listModels",
  "createModel",
  "importModel",
  "deleteModel",
  "getModel",
  "createModelVersion",
  "listSandboxes",
  "createSandbox",
  "deleteSandbox",
  "getSandbox",
  "patchSandbox",
  "extendSandbox",
  "pauseSandbox",
  "listSandboxSecurityEvents",
  "getSandboxSecurityOverview",
  "listAllTenantAdmins",
  "listTenantPlans",
  "createTenantPlan",
  "deleteTenantPlan",
  "getTenantPlan",
  "activateTenantPlan",
  "listTenantPlanAuditLogs",
  "disableTenantPlan",
  "getTenantPlanQuotaLimits",
  "updateTenantPlanQuotaLimits",
  "listTenantPlanBoundTenants",
  "listTenantMembers",
  "inviteTenantMember",
  "removeTenantMember",
  "getTenantMember",
  "listTenantRoles",
  "updateTenantRole",
  "getSsoConfig",
  "updateSsoConfig",
  "listWebhooks",
  "createWebhook",
  "deleteWebhook",
  "listWebhookDeliveries",
  "inviteTenantAdmin",
  "deleteTenantAdmin",
  "getTenantAdminDetail",
  "listTenantAdminAuditLogs",
  "disableTenantAdmin",
  "enableTenantAdmin",
  "resendTenantAdminInvitation",
  "resetTenantAdminPassword",
  "getTenantAdminRole",
  "updateTenantAdminRole",
  "bindTenantPlan",
  "transferTenantOwnership"
] as const;
export const paths = [
  "GET /gpu-containers",
  "POST /gpu-containers",
  "GET /gpu-containers/available-gpus",
  "DELETE /gpu-containers/{container_id}",
  "GET /gpu-containers/{container_id}",
  "PATCH /gpu-containers/{container_id}",
  "GET /gpu-containers/{container_id}/metrics",
  "POST /gpu-containers/{container_id}/rebuild",
  "POST /gpu-containers/{container_id}/rollback",
  "GET /gpu-containers/{container_id}/versions",
  "GET /inference-operations/{operation_id}",
  "GET /inference-services",
  "POST /inference-services",
  "DELETE /inference-services/{service_id}",
  "GET /inference-services/{service_id}",
  "PATCH /inference-services/{service_id}",
  "POST /inference-services/{service_id}/lifecycle",
  "GET /inference-services/{service_id}/logs",
  "PUT /inference-services/{service_id}/policies",
  "POST /inference-services/{service_id}/test",
  "GET /integrations",
  "POST /integrations",
  "POST /integrations/bots",
  "GET /knowledge-bases",
  "POST /knowledge-bases",
  "DELETE /knowledge-bases/{kb_id}",
  "GET /knowledge-bases/{kb_id}",
  "GET /knowledge-bases/{kb_id}/citations",
  "GET /knowledge-bases/{kb_id}/config",
  "PUT /knowledge-bases/{kb_id}/config",
  "GET /knowledge-bases/{kb_id}/documents",
  "POST /knowledge-bases/{kb_id}/documents",
  "DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
  "POST /knowledge-bases/{kb_id}/documents/{doc_id}/notify-uploaded",
  "POST /knowledge-bases/{kb_id}/documents/{doc_id}/reparse",
  "GET /knowledge-bases/{kb_id}/models",
  "PUT /knowledge-bases/{kb_id}/permissions",
  "POST /knowledge-bases/{kb_id}/query",
  "GET /knowledge-bases/{kb_id}/query/stream",
  "POST /knowledge-bases/{kb_id}/rebuild",
  "GET /knowledge-bases/{kb_id}/sessions",
  "GET /models",
  "POST /models",
  "POST /models/import",
  "DELETE /models/{model_id}",
  "GET /models/{model_id}",
  "POST /models/{model_id}/versions",
  "GET /sandboxes",
  "POST /sandboxes",
  "DELETE /sandboxes/{sandbox_id}",
  "GET /sandboxes/{sandbox_id}",
  "PATCH /sandboxes/{sandbox_id}",
  "POST /sandboxes/{sandbox_id}/extend",
  "POST /sandboxes/{sandbox_id}/pause",
  "GET /sandboxes/{sandbox_id}/security-events",
  "GET /sandboxes/{sandbox_id}/security-overview",
  "GET /tenant-admins",
  "GET /tenant-plans",
  "POST /tenant-plans",
  "DELETE /tenant-plans/{planId}",
  "GET /tenant-plans/{planId}",
  "POST /tenant-plans/{planId}/activate",
  "GET /tenant-plans/{planId}/audit-logs",
  "POST /tenant-plans/{planId}/disable",
  "GET /tenant-plans/{planId}/quota-limits",
  "PUT /tenant-plans/{planId}/quota-limits",
  "GET /tenant-plans/{planId}/tenants",
  "GET /tenant/members",
  "POST /tenant/members",
  "DELETE /tenant/members/{member_id}",
  "GET /tenant/members/{member_id}",
  "GET /tenant/roles",
  "PUT /tenant/roles/{role_id}",
  "GET /tenant/sso",
  "PUT /tenant/sso",
  "GET /tenant/webhooks",
  "POST /tenant/webhooks",
  "DELETE /tenant/webhooks/{webhook_id}",
  "GET /tenant/webhooks/{webhook_id}/deliveries",
  "POST /tenants/{tenantId}/admins/invite",
  "DELETE /tenants/{tenantId}/admins/{userId}",
  "GET /tenants/{tenantId}/admins/{userId}",
  "GET /tenants/{tenantId}/admins/{userId}/audit-logs",
  "POST /tenants/{tenantId}/admins/{userId}/disable",
  "POST /tenants/{tenantId}/admins/{userId}/enable",
  "POST /tenants/{tenantId}/admins/{userId}/invitation/resend",
  "POST /tenants/{tenantId}/admins/{userId}/reset-password",
  "GET /tenants/{tenantId}/admins/{userId}/role",
  "PUT /tenants/{tenantId}/admins/{userId}/role",
  "POST /tenants/{tenantId}/plan",
  "POST /tenants/{tenantId}/transfer-ownership"
] as const;
export const schemas = [
  "AdminDetail",
  "AdminListResponse",
  "AdminWithTenant",
  "AsyncTask",
  "AvailableGpu",
  "BindPlanRequest",
  "BoundTenant",
  "BoundTenantsResponse",
  "CreateGpuContainerRequest",
  "CreateInferenceEndpointRequest",
  "CreateInferenceServiceRequest",
  "CreateIntegrationBotRequest",
  "CreateIntegrationRequest",
  "CreateModelRequest",
  "CreateSandboxRequest",
  "CreateTenantPlanRequest",
  "CreateWebhookRequest",
  "CursorPage",
  "ErrorResponse",
  "ExtendSandboxRequest",
  "GetDocumentUploadURLRequest",
  "GetDocumentUploadURLResponse",
  "GpuContainer",
  "GpuContainerMetrics",
  "GpuContainerVersion",
  "IdempotentOnlyRequest",
  "IdempotentResult",
  "InferenceEndpoint",
  "InferenceService",
  "InferenceServiceAccelerator",
  "InferenceServiceEngine",
  "InferenceServiceEngineEnvVar",
  "InferenceServiceLifecycleRequest",
  "InferenceServiceLogEntry",
  "InferenceServiceLogListResponse",
  "InferenceServicePolicies",
  "InferenceServiceResources",
  "InferenceTestRequest",
  "InferenceTestResponse",
  "Integration",
  "IntegrationBot",
  "IntegrationListResponse",
  "InvitationResult",
  "InviteAdminRequest",
  "InviteMemberRequest",
  "KBCitation",
  "KBCitationListResponse",
  "KBConfig",
  "KBDocument",
  "KBQueryRequest",
  "KBQueryResponse",
  "KBSession",
  "KBSessionListResponse",
  "KnowledgeBase",
  "Model",
  "ModelList",
  "ModelVersion",
  "NotifyDocumentUploadedRequest",
  "PatchGpuContainerRequest",
  "PatchSandboxRequest",
  "PlanAuditLog",
  "PlanAuditLogListResponse",
  "PlanQuotaLimitInput",
  "PlanQuotaLimitView",
  "PlanQuotaLimitsResponse",
  "RebuildKnowledgeBaseRequest",
  "ReparseDocumentRequest",
  "ResendInvitationRequest",
  "ResetPasswordRequest",
  "Sandbox",
  "SecurityEvent",
  "SecurityOverview",
  "SsoConfig",
  "TenantAdminAuditLog",
  "TenantAdminAuditLogListResponse",
  "TenantMember",
  "TenantPlan",
  "TenantPlanListItem",
  "TenantPlanListResponse",
  "TenantRef",
  "TenantRole",
  "TransferOwnershipRequest",
  "UpdateInferenceServicePoliciesRequest",
  "UpdateInferenceServiceRequest",
  "UpdateKBConfigRequest",
  "UpdateKBPermissionsRequest",
  "UpdateQuotaLimitsRequest",
  "UpdateRoleRequest",
  "UpdateSsoConfigRequest",
  "UpdateTenantRoleRequest",
  "UserPermissions",
  "Webhook",
  "WebhookDelivery",
  "WebhookDeliveryListResponse"
] as const;
export const idempotencyOperations = [
  "createGpuContainer",
  "patchGpuContainer",
  "createInferenceService",
  "updateInferenceService",
  "applyInferenceServiceLifecycle",
  "updateInferenceServicePolicies",
  "testInferenceService",
  "createIntegration",
  "createIntegrationBot",
  "updateKnowledgeBaseConfig",
  "getDocumentUploadURL",
  "notifyDocumentUploaded",
  "reparseKnowledgeBaseDocument",
  "updateKnowledgeBasePermissions",
  "queryKnowledgeBase",
  "rebuildKnowledgeBase",
  "createSandbox",
  "patchSandbox",
  "extendSandbox",
  "createTenantPlan",
  "updateTenantPlanQuotaLimits",
  "inviteTenantMember",
  "updateTenantRole",
  "updateSsoConfig",
  "createWebhook",
  "inviteTenantAdmin",
  "disableTenantAdmin",
  "enableTenantAdmin",
  "resendTenantAdminInvitation",
  "resetTenantAdminPassword",
  "updateTenantAdminRole",
  "bindTenantPlan",
  "transferTenantOwnership"
] as const;
export const cursorPaginationOperations = [
  "listGpuContainers",
  "getInferenceServiceLogs",
  "listIntegrations",
  "listKnowledgeBaseCitations",
  "listKnowledgeBaseSessions",
  "listModels",
  "listSandboxes",
  "listAllTenantAdmins",
  "listTenantPlans",
  "listTenantPlanAuditLogs",
  "listWebhookDeliveries",
  "listTenantAdminAuditLogs"
] as const;
export const errorCodes = [
  "ACCELERATOR_SPEC_UNAVAILABLE",
  "BAD_REQUEST",
  "CONFLICT",
  "DEPENDENCY_UNAVAILABLE",
  "FEATURE_NOT_AVAILABLE",
  "FORBIDDEN",
  "IDEMPOTENCY_CONFLICT",
  "IMAGE_UNAVAILABLE",
  "INSUFFICIENT_CAPACITY",
  "INVALID_ARGUMENT",
  "INVALID_STATE_TRANSITION",
  "MODEL_INCOMPATIBLE",
  "MODEL_NOT_READY",
  "NAME_CONFLICT",
  "NOT_FOUND",
  "OPERATION_IN_PROGRESS",
  "PRECONDITION_FAILED",
  "RUNTIME_ERROR",
  "RUNTIME_TIMEOUT",
  "UNAUTHORIZED",
  "UNSUPPORTED_TOPOLOGY"
] as const;

export interface ClientOptions {
  baseURL?: string;
  token?: string;
}

export interface RequestOptions {
  body?: Record<string, unknown>;
  params?: Record<string, string | number | boolean | undefined>;
  headers?: Record<string, string>;
}

export interface APIError {
  code: string;
  message: string;
  request_id: string;
  details?: Record<string, unknown>;
}

export class Client {
  readonly baseURL: string;
  readonly token?: string;

  constructor(options: ClientOptions = {}) {
    this.baseURL = options.baseURL || serverURL;
    this.token = options.token;
  }

  hasOperation(operationID: string): boolean {
    return operations.includes(operationID as typeof operations[number]);
  }

  async request<T = unknown>(method: string, path: string, options: RequestOptions = {}): Promise<T> {
    const response = await fetch(this.url(path, options.params), {
      method: method.toUpperCase(),
      headers: this.headers(options.headers, options.body !== undefined),
      body: options.body === undefined ? undefined : JSON.stringify(options.body),
    });
    const payload = await this.decodeResponse(response);
    if (!response.ok) {
      if (payload && typeof payload === "object" && "code" in payload && "message" in payload) {
        const data = payload as Record<string, unknown>;
        throw apiError(String(data.code), String(data.message), String(data.request_id || ""), data.details as Record<string, unknown> | undefined);
      }
      throw new Error(`ANI API request failed: ${response.status}`);
    }
    return payload as T;
  }

  private url(path: string, params?: RequestOptions["params"]): string {
    const base = this.baseURL.replace(/\/$/, "");
    const relative = path.startsWith("/") ? path : `/${path}`;
    const query = new URLSearchParams();
    for (const [key, value] of Object.entries(params || {})) {
      if (value !== undefined) {
        query.set(key, String(value));
      }
    }
    const suffix = query.toString();
    return `${base}${relative}${suffix ? `?${suffix}` : ""}`;
  }

  private headers(headers?: Record<string, string>, hasBody = false): Record<string, string> {
    return {
      Accept: "application/json",
      ...(hasBody ? { "Content-Type": "application/json" } : {}),
      ...(this.token ? { Authorization: `Bearer ${this.token}` } : {}),
      ...(headers || {}),
    };
  }

  private async decodeResponse(response: Response): Promise<unknown> {
    if (response.status === 204) {
      return undefined;
    }
    const text = await response.text();
    if (!text) {
      return undefined;
    }
    const contentType = response.headers.get("content-type") || "";
    return contentType.includes("application/json") ? JSON.parse(text) : text;
  }
}

export function newIdempotencyKey(prefix = "ani"): string {
  const safePrefix = prefix || "ani";
  const cryptoObj = globalThis.crypto;
  if (cryptoObj?.randomUUID) {
    return `${safePrefix}_${cryptoObj.randomUUID()}`;
  }
  const bytes = new Uint8Array(16);
  if (cryptoObj?.getRandomValues) {
    cryptoObj.getRandomValues(bytes);
  } else {
    for (let i = 0; i < bytes.length; i += 1) {
      bytes[i] = Math.floor(Math.random() * 256);
    }
  }
  return `${safePrefix}_${Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("")}`;
}

export function withIdempotencyKey<T extends Record<string, unknown>>(body: T, key = newIdempotencyKey()): T & { idempotency_key: string } {
  return { ...body, idempotency_key: key };
}

export function cursorParams(limit?: number, cursor?: string): Record<string, string> {
  const params: Record<string, string> = {};
  if (limit !== undefined && limit > 0) {
    params.limit = String(limit);
  }
  if (cursor) {
    params.cursor = cursor;
  }
  return params;
}

export function isAPIErrorCode(code: string): boolean {
  return errorCodes.includes(code as typeof errorCodes[number]);
}

export function apiError(code: string, message: string, requestID = "", details?: Record<string, unknown>): APIError {
  return { code, message, request_id: requestID, ...(details ? { details } : {}) };
}
