# Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
import json
import secrets
from urllib import error, parse, request

LAYER = "services"
TITLE = "KuberCloud ANI Services API"
VERSION = "1.0.0"
SERVER_URL = "https://{host}/api/v1/svc"
OPERATIONS = [
    "listGpuContainers",
    "createGpuContainer",
    "listAvailableGpus",
    "deleteGpuContainer",
    "getGpuContainer",
    "patchGpuContainer",
    "getGpuContainerMetrics",
    "rebuildGpuContainer",
    "rollbackGpuContainer",
    "listGpuContainerVersions",
    "getInferenceOperation",
    "listInferenceServices",
    "createInferenceService",
    "deleteInferenceService",
    "getInferenceService",
    "updateInferenceService",
    "applyInferenceServiceLifecycle",
    "getInferenceServiceLogs",
    "updateInferenceServicePolicies",
    "testInferenceService",
    "listIntegrations",
    "createIntegration",
    "createIntegrationBot",
    "listKnowledgeBases",
    "createKnowledgeBase",
    "deleteKnowledgeBase",
    "getKnowledgeBase",
    "listKnowledgeBaseCitations",
    "getKnowledgeBaseConfig",
    "updateKnowledgeBaseConfig",
    "listKnowledgeBaseDocuments",
    "getDocumentUploadURL",
    "deleteKnowledgeBaseDocument",
    "notifyDocumentUploaded",
    "reparseKnowledgeBaseDocument",
    "listKnowledgeBaseModels",
    "updateKnowledgeBasePermissions",
    "queryKnowledgeBase",
    "streamQueryKnowledgeBase",
    "rebuildKnowledgeBase",
    "listKnowledgeBaseSessions",
    "listModels",
    "createModel",
    "importModel",
    "deleteModel",
    "getModel",
    "createModelVersion",
    "listSandboxes",
    "createSandbox",
    "deleteSandbox",
    "getSandbox",
    "patchSandbox",
    "extendSandbox",
    "pauseSandbox",
    "listSandboxSecurityEvents",
    "getSandboxSecurityOverview",
    "listAllTenantAdmins",
    "listTenantPlans",
    "createTenantPlan",
    "deleteTenantPlan",
    "getTenantPlan",
    "activateTenantPlan",
    "listTenantPlanAuditLogs",
    "disableTenantPlan",
    "getTenantPlanQuotaLimits",
    "updateTenantPlanQuotaLimits",
    "listTenantPlanBoundTenants",
    "listTenantMembers",
    "inviteTenantMember",
    "removeTenantMember",
    "getTenantMember",
    "listTenantRoles",
    "updateTenantRole",
    "getSsoConfig",
    "updateSsoConfig",
    "listWebhooks",
    "createWebhook",
    "deleteWebhook",
    "listWebhookDeliveries",
    "inviteTenantAdmin",
    "deleteTenantAdmin",
    "getTenantAdminDetail",
    "listTenantAdminAuditLogs",
    "disableTenantAdmin",
    "enableTenantAdmin",
    "resendTenantAdminInvitation",
    "resetTenantAdminPassword",
    "getTenantAdminRole",
    "updateTenantAdminRole",
    "bindTenantPlan",
    "transferTenantOwnership"
]
PATHS = [
    "GET /gpu-containers",
    "POST /gpu-containers",
    "GET /gpu-containers/available-gpus",
    "DELETE /gpu-containers/{container_id}",
    "GET /gpu-containers/{container_id}",
    "PATCH /gpu-containers/{container_id}",
    "GET /gpu-containers/{container_id}/metrics",
    "POST /gpu-containers/{container_id}/rebuild",
    "POST /gpu-containers/{container_id}/rollback",
    "GET /gpu-containers/{container_id}/versions",
    "GET /inference-operations/{operation_id}",
    "GET /inference-services",
    "POST /inference-services",
    "DELETE /inference-services/{service_id}",
    "GET /inference-services/{service_id}",
    "PATCH /inference-services/{service_id}",
    "POST /inference-services/{service_id}/lifecycle",
    "GET /inference-services/{service_id}/logs",
    "PUT /inference-services/{service_id}/policies",
    "POST /inference-services/{service_id}/test",
    "GET /integrations",
    "POST /integrations",
    "POST /integrations/bots",
    "GET /knowledge-bases",
    "POST /knowledge-bases",
    "DELETE /knowledge-bases/{kb_id}",
    "GET /knowledge-bases/{kb_id}",
    "GET /knowledge-bases/{kb_id}/citations",
    "GET /knowledge-bases/{kb_id}/config",
    "PUT /knowledge-bases/{kb_id}/config",
    "GET /knowledge-bases/{kb_id}/documents",
    "POST /knowledge-bases/{kb_id}/documents",
    "DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
    "POST /knowledge-bases/{kb_id}/documents/{doc_id}/notify-uploaded",
    "POST /knowledge-bases/{kb_id}/documents/{doc_id}/reparse",
    "GET /knowledge-bases/{kb_id}/models",
    "PUT /knowledge-bases/{kb_id}/permissions",
    "POST /knowledge-bases/{kb_id}/query",
    "GET /knowledge-bases/{kb_id}/query/stream",
    "POST /knowledge-bases/{kb_id}/rebuild",
    "GET /knowledge-bases/{kb_id}/sessions",
    "GET /models",
    "POST /models",
    "POST /models/import",
    "DELETE /models/{model_id}",
    "GET /models/{model_id}",
    "POST /models/{model_id}/versions",
    "GET /sandboxes",
    "POST /sandboxes",
    "DELETE /sandboxes/{sandbox_id}",
    "GET /sandboxes/{sandbox_id}",
    "PATCH /sandboxes/{sandbox_id}",
    "POST /sandboxes/{sandbox_id}/extend",
    "POST /sandboxes/{sandbox_id}/pause",
    "GET /sandboxes/{sandbox_id}/security-events",
    "GET /sandboxes/{sandbox_id}/security-overview",
    "GET /tenant-admins",
    "GET /tenant-plans",
    "POST /tenant-plans",
    "DELETE /tenant-plans/{planId}",
    "GET /tenant-plans/{planId}",
    "POST /tenant-plans/{planId}/activate",
    "GET /tenant-plans/{planId}/audit-logs",
    "POST /tenant-plans/{planId}/disable",
    "GET /tenant-plans/{planId}/quota-limits",
    "PUT /tenant-plans/{planId}/quota-limits",
    "GET /tenant-plans/{planId}/tenants",
    "GET /tenant/members",
    "POST /tenant/members",
    "DELETE /tenant/members/{member_id}",
    "GET /tenant/members/{member_id}",
    "GET /tenant/roles",
    "PUT /tenant/roles/{role_id}",
    "GET /tenant/sso",
    "PUT /tenant/sso",
    "GET /tenant/webhooks",
    "POST /tenant/webhooks",
    "DELETE /tenant/webhooks/{webhook_id}",
    "GET /tenant/webhooks/{webhook_id}/deliveries",
    "POST /tenants/{tenantId}/admins/invite",
    "DELETE /tenants/{tenantId}/admins/{userId}",
    "GET /tenants/{tenantId}/admins/{userId}",
    "GET /tenants/{tenantId}/admins/{userId}/audit-logs",
    "POST /tenants/{tenantId}/admins/{userId}/disable",
    "POST /tenants/{tenantId}/admins/{userId}/enable",
    "POST /tenants/{tenantId}/admins/{userId}/invitation/resend",
    "POST /tenants/{tenantId}/admins/{userId}/reset-password",
    "GET /tenants/{tenantId}/admins/{userId}/role",
    "PUT /tenants/{tenantId}/admins/{userId}/role",
    "POST /tenants/{tenantId}/plan",
    "POST /tenants/{tenantId}/transfer-ownership"
]
SCHEMAS = [
    "AdminDetail",
    "AdminListResponse",
    "AdminWithTenant",
    "AsyncTask",
    "AvailableGpu",
    "BindPlanRequest",
    "BoundTenant",
    "BoundTenantsResponse",
    "CreateGpuContainerRequest",
    "CreateInferenceEndpointRequest",
    "CreateInferenceServiceRequest",
    "CreateIntegrationBotRequest",
    "CreateIntegrationRequest",
    "CreateModelRequest",
    "CreateSandboxRequest",
    "CreateTenantPlanRequest",
    "CreateWebhookRequest",
    "CursorPage",
    "ErrorResponse",
    "ExtendSandboxRequest",
    "GetDocumentUploadURLRequest",
    "GetDocumentUploadURLResponse",
    "GpuContainer",
    "GpuContainerMetrics",
    "GpuContainerVersion",
    "IdempotentOnlyRequest",
    "IdempotentResult",
    "InferenceEndpoint",
    "InferenceService",
    "InferenceServiceAccelerator",
    "InferenceServiceEngine",
    "InferenceServiceEngineEnvVar",
    "InferenceServiceLifecycleRequest",
    "InferenceServiceLogEntry",
    "InferenceServiceLogListResponse",
    "InferenceServicePolicies",
    "InferenceServiceResources",
    "InferenceTestRequest",
    "InferenceTestResponse",
    "Integration",
    "IntegrationBot",
    "IntegrationListResponse",
    "InvitationResult",
    "InviteAdminRequest",
    "InviteMemberRequest",
    "KBCitation",
    "KBCitationListResponse",
    "KBConfig",
    "KBDocument",
    "KBQueryRequest",
    "KBQueryResponse",
    "KBSession",
    "KBSessionListResponse",
    "KnowledgeBase",
    "Model",
    "ModelList",
    "ModelVersion",
    "NotifyDocumentUploadedRequest",
    "PatchGpuContainerRequest",
    "PatchSandboxRequest",
    "PlanAuditLog",
    "PlanAuditLogListResponse",
    "PlanQuotaLimitInput",
    "PlanQuotaLimitView",
    "PlanQuotaLimitsResponse",
    "RebuildKnowledgeBaseRequest",
    "ReparseDocumentRequest",
    "ResendInvitationRequest",
    "ResetPasswordRequest",
    "Sandbox",
    "SecurityEvent",
    "SecurityOverview",
    "SsoConfig",
    "TenantAdminAuditLog",
    "TenantAdminAuditLogListResponse",
    "TenantMember",
    "TenantPlan",
    "TenantPlanListItem",
    "TenantPlanListResponse",
    "TenantRef",
    "TenantRole",
    "TransferOwnershipRequest",
    "UpdateInferenceServicePoliciesRequest",
    "UpdateInferenceServiceRequest",
    "UpdateKBConfigRequest",
    "UpdateKBPermissionsRequest",
    "UpdateQuotaLimitsRequest",
    "UpdateRoleRequest",
    "UpdateSsoConfigRequest",
    "UpdateTenantRoleRequest",
    "UserPermissions",
    "Webhook",
    "WebhookDelivery",
    "WebhookDeliveryListResponse"
]
IDEMPOTENCY_OPERATIONS = [
    "createGpuContainer",
    "patchGpuContainer",
    "createInferenceService",
    "updateInferenceService",
    "applyInferenceServiceLifecycle",
    "updateInferenceServicePolicies",
    "testInferenceService",
    "createIntegration",
    "createIntegrationBot",
    "updateKnowledgeBaseConfig",
    "getDocumentUploadURL",
    "notifyDocumentUploaded",
    "reparseKnowledgeBaseDocument",
    "updateKnowledgeBasePermissions",
    "queryKnowledgeBase",
    "rebuildKnowledgeBase",
    "createSandbox",
    "patchSandbox",
    "extendSandbox",
    "createTenantPlan",
    "updateTenantPlanQuotaLimits",
    "inviteTenantMember",
    "updateTenantRole",
    "updateSsoConfig",
    "createWebhook",
    "inviteTenantAdmin",
    "disableTenantAdmin",
    "enableTenantAdmin",
    "resendTenantAdminInvitation",
    "resetTenantAdminPassword",
    "updateTenantAdminRole",
    "bindTenantPlan",
    "transferTenantOwnership"
]
CURSOR_PAGINATION_OPERATIONS = [
    "listGpuContainers",
    "getInferenceServiceLogs",
    "listIntegrations",
    "listKnowledgeBaseCitations",
    "listKnowledgeBaseSessions",
    "listModels",
    "listSandboxes",
    "listAllTenantAdmins",
    "listTenantPlans",
    "listTenantPlanAuditLogs",
    "listWebhookDeliveries",
    "listTenantAdminAuditLogs"
]
ERROR_CODES = [
    "ACCELERATOR_SPEC_UNAVAILABLE",
    "BAD_REQUEST",
    "CONFLICT",
    "DEPENDENCY_UNAVAILABLE",
    "FEATURE_NOT_AVAILABLE",
    "FORBIDDEN",
    "IDEMPOTENCY_CONFLICT",
    "IMAGE_UNAVAILABLE",
    "INSUFFICIENT_CAPACITY",
    "INVALID_ARGUMENT",
    "INVALID_STATE_TRANSITION",
    "MODEL_INCOMPATIBLE",
    "MODEL_NOT_READY",
    "NAME_CONFLICT",
    "NOT_FOUND",
    "OPERATION_IN_PROGRESS",
    "PRECONDITION_FAILED",
    "RUNTIME_ERROR",
    "RUNTIME_TIMEOUT",
    "UNAUTHORIZED",
    "UNSUPPORTED_TOPOLOGY"
]


class APIError(Exception):
    def __init__(self, code: str, message: str, request_id: str = "", details: dict | None = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.request_id = request_id
        self.details = dict(details or {})

    def to_dict(self) -> dict:
        payload = {"code": self.code, "message": self.message, "request_id": self.request_id}
        if self.details:
            payload["details"] = self.details
        return payload


class Client:
    def __init__(self, base_url: str | None = None, token: str | None = None, timeout: float = 10.0):
        self.base_url = base_url or SERVER_URL
        self.token = token
        self.timeout = timeout

    def has_operation(self, operation_id: str) -> bool:
        return operation_id in OPERATIONS

    def request(
        self,
        method: str,
        path: str,
        body: dict | None = None,
        params: dict | None = None,
        headers: dict | None = None,
    ) -> dict | list | str | None:
        req = request.Request(
            self._url(path, params),
            data=self._encode_body(body),
            method=method.upper(),
            headers=self._headers(headers, body is not None),
        )
        try:
            with request.urlopen(req, timeout=self.timeout) as response:
                return self._decode_response(response.read(), response.headers.get("Content-Type", ""))
        except error.HTTPError as exc:
            payload = self._decode_response(exc.read(), exc.headers.get("Content-Type", ""))
            if isinstance(payload, dict) and "code" in payload and "message" in payload:
                raise APIError(
                    str(payload["code"]),
                    str(payload["message"]),
                    str(payload.get("request_id", "")),
                    payload.get("details") if isinstance(payload.get("details"), dict) else None,
                ) from exc
            raise

    def _url(self, path: str, params: dict | None = None) -> str:
        base = self.base_url.rstrip("/")
        relative = "/" + path.lstrip("/")
        query = parse.urlencode({key: value for key, value in (params or {}).items() if value is not None})
        return f"{base}{relative}{'?' + query if query else ''}"

    def _headers(self, headers: dict | None = None, has_body: bool = False) -> dict:
        merged = {"Accept": "application/json"}
        if has_body:
            merged["Content-Type"] = "application/json"
        if self.token:
            merged["Authorization"] = f"Bearer {self.token}"
        merged.update(headers or {})
        return merged

    def _encode_body(self, body: dict | None) -> bytes | None:
        if body is None:
            return None
        return json.dumps(body).encode("utf-8")

    def _decode_response(self, payload: bytes, content_type: str) -> dict | list | str | None:
        if not payload:
            return None
        text = payload.decode("utf-8")
        if "application/json" in content_type:
            return json.loads(text)
        return text


def new_idempotency_key(prefix: str = "ani") -> str:
    prefix = prefix or "ani"
    return f"{prefix}_{secrets.token_hex(16)}"


def with_idempotency_key(body: dict | None = None, key: str | None = None) -> dict:
    payload = dict(body or {})
    payload["idempotency_key"] = key or new_idempotency_key()
    return payload


def cursor_params(limit: int | None = None, cursor: str | None = None) -> dict:
    params = {}
    if limit is not None and limit > 0:
        params["limit"] = limit
    if cursor:
        params["cursor"] = cursor
    return params


def is_api_error_code(code: str) -> bool:
    return code in ERROR_CODES
