// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package anisdk

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const Layer = "services"
const Title = "KuberCloud ANI Services API"
const Version = "1.0.0"
const ServerURL = "https://{host}/api/v1/svc"

var Operations = []string{
	"listGpuContainers",
	"createGpuContainer",
	"listAvailableGpus",
	"deleteGpuContainer",
	"getGpuContainer",
	"patchGpuContainer",
	"getGpuContainerMetrics",
	"rebuildGpuContainer",
	"rollbackGpuContainer",
	"listGpuContainerVersions",
	"getInferenceOperation",
	"listInferenceServices",
	"createInferenceService",
	"deleteInferenceService",
	"getInferenceService",
	"updateInferenceService",
	"applyInferenceServiceLifecycle",
	"getInferenceServiceLogs",
	"updateInferenceServicePolicies",
	"testInferenceService",
	"listIntegrations",
	"createIntegration",
	"createIntegrationBot",
	"listKnowledgeBases",
	"createKnowledgeBase",
	"deleteKnowledgeBase",
	"getKnowledgeBase",
	"listKnowledgeBaseCitations",
	"getKnowledgeBaseConfig",
	"updateKnowledgeBaseConfig",
	"listKnowledgeBaseDocuments",
	"getDocumentUploadURL",
	"deleteKnowledgeBaseDocument",
	"notifyDocumentUploaded",
	"reparseKnowledgeBaseDocument",
	"listKnowledgeBaseModels",
	"updateKnowledgeBasePermissions",
	"queryKnowledgeBase",
	"streamQueryKnowledgeBase",
	"rebuildKnowledgeBase",
	"listKnowledgeBaseSessions",
	"listModels",
	"createModel",
	"importModel",
	"deleteModel",
	"getModel",
	"createModelVersion",
	"listSandboxes",
	"createSandbox",
	"deleteSandbox",
	"getSandbox",
	"patchSandbox",
	"extendSandbox",
	"pauseSandbox",
	"listSandboxSecurityEvents",
	"getSandboxSecurityOverview",
	"listAllTenantAdmins",
	"listTenantPlans",
	"createTenantPlan",
	"deleteTenantPlan",
	"getTenantPlan",
	"activateTenantPlan",
	"listTenantPlanAuditLogs",
	"disableTenantPlan",
	"getTenantPlanQuotaLimits",
	"updateTenantPlanQuotaLimits",
	"listTenantPlanBoundTenants",
	"listTenantMembers",
	"inviteTenantMember",
	"removeTenantMember",
	"getTenantMember",
	"listTenantRoles",
	"updateTenantRole",
	"getSsoConfig",
	"updateSsoConfig",
	"listWebhooks",
	"createWebhook",
	"deleteWebhook",
	"listWebhookDeliveries",
	"inviteTenantAdmin",
	"deleteTenantAdmin",
	"getTenantAdminDetail",
	"listTenantAdminAuditLogs",
	"disableTenantAdmin",
	"enableTenantAdmin",
	"resendTenantAdminInvitation",
	"resetTenantAdminPassword",
	"getTenantAdminRole",
	"updateTenantAdminRole",
	"bindTenantPlan",
	"transferTenantOwnership",
}
var Paths = []string{
	"GET /gpu-containers",
	"POST /gpu-containers",
	"GET /gpu-containers/available-gpus",
	"DELETE /gpu-containers/{container_id}",
	"GET /gpu-containers/{container_id}",
	"PATCH /gpu-containers/{container_id}",
	"GET /gpu-containers/{container_id}/metrics",
	"POST /gpu-containers/{container_id}/rebuild",
	"POST /gpu-containers/{container_id}/rollback",
	"GET /gpu-containers/{container_id}/versions",
	"GET /inference-operations/{operation_id}",
	"GET /inference-services",
	"POST /inference-services",
	"DELETE /inference-services/{service_id}",
	"GET /inference-services/{service_id}",
	"PATCH /inference-services/{service_id}",
	"POST /inference-services/{service_id}/lifecycle",
	"GET /inference-services/{service_id}/logs",
	"PUT /inference-services/{service_id}/policies",
	"POST /inference-services/{service_id}/test",
	"GET /integrations",
	"POST /integrations",
	"POST /integrations/bots",
	"GET /knowledge-bases",
	"POST /knowledge-bases",
	"DELETE /knowledge-bases/{kb_id}",
	"GET /knowledge-bases/{kb_id}",
	"GET /knowledge-bases/{kb_id}/citations",
	"GET /knowledge-bases/{kb_id}/config",
	"PUT /knowledge-bases/{kb_id}/config",
	"GET /knowledge-bases/{kb_id}/documents",
	"POST /knowledge-bases/{kb_id}/documents",
	"DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
	"POST /knowledge-bases/{kb_id}/documents/{doc_id}/notify-uploaded",
	"POST /knowledge-bases/{kb_id}/documents/{doc_id}/reparse",
	"GET /knowledge-bases/{kb_id}/models",
	"PUT /knowledge-bases/{kb_id}/permissions",
	"POST /knowledge-bases/{kb_id}/query",
	"GET /knowledge-bases/{kb_id}/query/stream",
	"POST /knowledge-bases/{kb_id}/rebuild",
	"GET /knowledge-bases/{kb_id}/sessions",
	"GET /models",
	"POST /models",
	"POST /models/import",
	"DELETE /models/{model_id}",
	"GET /models/{model_id}",
	"POST /models/{model_id}/versions",
	"GET /sandboxes",
	"POST /sandboxes",
	"DELETE /sandboxes/{sandbox_id}",
	"GET /sandboxes/{sandbox_id}",
	"PATCH /sandboxes/{sandbox_id}",
	"POST /sandboxes/{sandbox_id}/extend",
	"POST /sandboxes/{sandbox_id}/pause",
	"GET /sandboxes/{sandbox_id}/security-events",
	"GET /sandboxes/{sandbox_id}/security-overview",
	"GET /tenant-admins",
	"GET /tenant-plans",
	"POST /tenant-plans",
	"DELETE /tenant-plans/{planId}",
	"GET /tenant-plans/{planId}",
	"POST /tenant-plans/{planId}/activate",
	"GET /tenant-plans/{planId}/audit-logs",
	"POST /tenant-plans/{planId}/disable",
	"GET /tenant-plans/{planId}/quota-limits",
	"PUT /tenant-plans/{planId}/quota-limits",
	"GET /tenant-plans/{planId}/tenants",
	"GET /tenant/members",
	"POST /tenant/members",
	"DELETE /tenant/members/{member_id}",
	"GET /tenant/members/{member_id}",
	"GET /tenant/roles",
	"PUT /tenant/roles/{role_id}",
	"GET /tenant/sso",
	"PUT /tenant/sso",
	"GET /tenant/webhooks",
	"POST /tenant/webhooks",
	"DELETE /tenant/webhooks/{webhook_id}",
	"GET /tenant/webhooks/{webhook_id}/deliveries",
	"POST /tenants/{tenantId}/admins/invite",
	"DELETE /tenants/{tenantId}/admins/{userId}",
	"GET /tenants/{tenantId}/admins/{userId}",
	"GET /tenants/{tenantId}/admins/{userId}/audit-logs",
	"POST /tenants/{tenantId}/admins/{userId}/disable",
	"POST /tenants/{tenantId}/admins/{userId}/enable",
	"POST /tenants/{tenantId}/admins/{userId}/invitation/resend",
	"POST /tenants/{tenantId}/admins/{userId}/reset-password",
	"GET /tenants/{tenantId}/admins/{userId}/role",
	"PUT /tenants/{tenantId}/admins/{userId}/role",
	"POST /tenants/{tenantId}/plan",
	"POST /tenants/{tenantId}/transfer-ownership",
}
var Schemas = []string{
	"AdminDetail",
	"AdminListResponse",
	"AdminWithTenant",
	"AsyncTask",
	"AvailableGpu",
	"BindPlanRequest",
	"BoundTenant",
	"BoundTenantsResponse",
	"CreateGpuContainerRequest",
	"CreateInferenceEndpointRequest",
	"CreateInferenceServiceRequest",
	"CreateIntegrationBotRequest",
	"CreateIntegrationRequest",
	"CreateModelRequest",
	"CreateSandboxRequest",
	"CreateTenantPlanRequest",
	"CreateWebhookRequest",
	"CursorPage",
	"ErrorResponse",
	"ExtendSandboxRequest",
	"GetDocumentUploadURLRequest",
	"GetDocumentUploadURLResponse",
	"GpuContainer",
	"GpuContainerMetrics",
	"GpuContainerVersion",
	"IdempotentOnlyRequest",
	"IdempotentResult",
	"InferenceEndpoint",
	"InferenceService",
	"InferenceServiceAccelerator",
	"InferenceServiceEngine",
	"InferenceServiceEngineEnvVar",
	"InferenceServiceLifecycleRequest",
	"InferenceServiceLogEntry",
	"InferenceServiceLogListResponse",
	"InferenceServicePolicies",
	"InferenceServiceResources",
	"InferenceTestRequest",
	"InferenceTestResponse",
	"Integration",
	"IntegrationBot",
	"IntegrationListResponse",
	"InvitationResult",
	"InviteAdminRequest",
	"InviteMemberRequest",
	"KBCitation",
	"KBCitationListResponse",
	"KBConfig",
	"KBDocument",
	"KBQueryRequest",
	"KBQueryResponse",
	"KBSession",
	"KBSessionListResponse",
	"KnowledgeBase",
	"Model",
	"ModelList",
	"ModelVersion",
	"NotifyDocumentUploadedRequest",
	"PatchGpuContainerRequest",
	"PatchSandboxRequest",
	"PlanAuditLog",
	"PlanAuditLogListResponse",
	"PlanQuotaLimitInput",
	"PlanQuotaLimitView",
	"PlanQuotaLimitsResponse",
	"RebuildKnowledgeBaseRequest",
	"ReparseDocumentRequest",
	"ResendInvitationRequest",
	"ResetPasswordRequest",
	"Sandbox",
	"SecurityEvent",
	"SecurityOverview",
	"SsoConfig",
	"TenantAdminAuditLog",
	"TenantAdminAuditLogListResponse",
	"TenantMember",
	"TenantPlan",
	"TenantPlanListItem",
	"TenantPlanListResponse",
	"TenantRef",
	"TenantRole",
	"TransferOwnershipRequest",
	"UpdateInferenceServicePoliciesRequest",
	"UpdateInferenceServiceRequest",
	"UpdateKBConfigRequest",
	"UpdateKBPermissionsRequest",
	"UpdateQuotaLimitsRequest",
	"UpdateRoleRequest",
	"UpdateSsoConfigRequest",
	"UpdateTenantRoleRequest",
	"UserPermissions",
	"Webhook",
	"WebhookDelivery",
	"WebhookDeliveryListResponse",
}
var IdempotencyOperations = []string{
	"createGpuContainer",
	"patchGpuContainer",
	"createInferenceService",
	"updateInferenceService",
	"applyInferenceServiceLifecycle",
	"updateInferenceServicePolicies",
	"testInferenceService",
	"createIntegration",
	"createIntegrationBot",
	"updateKnowledgeBaseConfig",
	"getDocumentUploadURL",
	"notifyDocumentUploaded",
	"reparseKnowledgeBaseDocument",
	"updateKnowledgeBasePermissions",
	"queryKnowledgeBase",
	"rebuildKnowledgeBase",
	"createSandbox",
	"patchSandbox",
	"extendSandbox",
	"createTenantPlan",
	"updateTenantPlanQuotaLimits",
	"inviteTenantMember",
	"updateTenantRole",
	"updateSsoConfig",
	"createWebhook",
	"inviteTenantAdmin",
	"disableTenantAdmin",
	"enableTenantAdmin",
	"resendTenantAdminInvitation",
	"resetTenantAdminPassword",
	"updateTenantAdminRole",
	"bindTenantPlan",
	"transferTenantOwnership",
}
var CursorPaginationOperations = []string{
	"listGpuContainers",
	"getInferenceServiceLogs",
	"listIntegrations",
	"listKnowledgeBaseCitations",
	"listKnowledgeBaseSessions",
	"listModels",
	"listSandboxes",
	"listAllTenantAdmins",
	"listTenantPlans",
	"listTenantPlanAuditLogs",
	"listWebhookDeliveries",
	"listTenantAdminAuditLogs",
}
var ErrorCodes = []string{
	"ACCELERATOR_SPEC_UNAVAILABLE",
	"BAD_REQUEST",
	"CONFLICT",
	"DEPENDENCY_UNAVAILABLE",
	"FEATURE_NOT_AVAILABLE",
	"FORBIDDEN",
	"IDEMPOTENCY_CONFLICT",
	"IMAGE_UNAVAILABLE",
	"INSUFFICIENT_CAPACITY",
	"INVALID_ARGUMENT",
	"INVALID_STATE_TRANSITION",
	"MODEL_INCOMPATIBLE",
	"MODEL_NOT_READY",
	"NAME_CONFLICT",
	"NOT_FOUND",
	"OPERATION_IN_PROGRESS",
	"PRECONDITION_FAILED",
	"RUNTIME_ERROR",
	"RUNTIME_TIMEOUT",
	"UNAUTHORIZED",
	"UNSUPPORTED_TOPOLOGY",
}

type APIError struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id"`
	Details   map[string]any `json:"details,omitempty"`
}

func (err APIError) Error() string {
	if err.Message == "" {
		return err.Code
	}
	if err.Code == "" {
		return err.Message
	}
	return err.Code + ": " + err.Message
}

type Client struct {
	BaseURL string
	Token   string
}

type RequestOptions struct {
	Body    map[string]any
	Params  map[string]string
	Headers map[string]string
}

func NewClient(baseURL string, token string) Client {
	if baseURL == "" {
		baseURL = ServerURL
	}
	return Client{BaseURL: baseURL, Token: token}
}

func (client Client) Request(method string, path string, options RequestOptions) (any, error) {
	requestURL, err := client.requestURL(path, options.Params)
	if err != nil {
		return nil, err
	}
	var body io.Reader
	if options.Body != nil {
		payload, err := json.Marshal(options.Body)
		if err != nil {
			return nil, fmt.Errorf("encode request body: %w", err)
		}
		body = bytes.NewReader(payload)
	}
	req, err := http.NewRequest(strings.ToUpper(method), requestURL, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if client.Token != "" {
		req.Header.Set("Authorization", "Bearer "+client.Token)
	}
	for key, value := range options.Headers {
		req.Header.Set(key, value)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	return decodeResponse(resp)
}

func (client Client) requestURL(path string, params map[string]string) (string, error) {
	base := strings.TrimRight(client.BaseURL, "/")
	relative := "/" + strings.TrimLeft(path, "/")
	parsed, err := url.Parse(base + relative)
	if err != nil {
		return "", err
	}
	query := parsed.Query()
	for key, value := range params {
		if value != "" {
			query.Set(key, value)
		}
	}
	parsed.RawQuery = query.Encode()
	return parsed.String(), nil
}

func decodeResponse(resp *http.Response) (any, error) {
	if resp.StatusCode == http.StatusNoContent {
		return nil, nil
	}
	payload, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if len(payload) == 0 {
		if resp.StatusCode >= 400 {
			return nil, fmt.Errorf("ANI API request failed: %d", resp.StatusCode)
		}
		return nil, nil
	}
	var decoded any
	if strings.Contains(resp.Header.Get("Content-Type"), "application/json") {
		if err := json.Unmarshal(payload, &decoded); err != nil {
			return nil, err
		}
	} else {
		decoded = string(payload)
	}
	if resp.StatusCode >= 400 {
		if data, ok := decoded.(map[string]any); ok {
			code, _ := data["code"].(string)
			message, _ := data["message"].(string)
			requestID, _ := data["request_id"].(string)
			details, _ := data["details"].(map[string]any)
			if code != "" && message != "" {
				return nil, APIError{Code: code, Message: message, RequestID: requestID, Details: details}
			}
		}
		return nil, fmt.Errorf("ANI API request failed: %d", resp.StatusCode)
	}
	return decoded, nil
}

func HasOperation(operationID string) bool {
	for _, operation := range Operations {
		if operation == operationID {
			return true
		}
	}
	return false
}

func NewIdempotencyKey(prefix string) (string, error) {
	if prefix == "" {
		prefix = "ani"
	}
	random := make([]byte, 16)
	if _, err := rand.Read(random); err != nil {
		return "", fmt.Errorf("generate idempotency key: %w", err)
	}
	return prefix + "_" + hex.EncodeToString(random), nil
}

func WithIdempotencyKey(body map[string]any, key string) (map[string]any, error) {
	if body == nil {
		body = map[string]any{}
	}
	if key == "" {
		generated, err := NewIdempotencyKey("ani")
		if err != nil {
			return nil, err
		}
		key = generated
	}
	body["idempotency_key"] = key
	return body, nil
}

func CursorParams(limit int, cursor string) map[string]string {
	params := map[string]string{}
	if limit > 0 {
		params["limit"] = fmt.Sprintf("%d", limit)
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	return params
}

func IsAPIErrorCode(code string) bool {
	for _, item := range ErrorCodes {
		if item == code {
			return true
		}
	}
	return false
}

func NewAPIError(code string, message string, requestID string, details map[string]any) APIError {
	return APIError{Code: code, Message: message, RequestID: requestID, Details: details}
}
