// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package com.kubercloud.ani.services;

import java.security.SecureRandom;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class ApiClient {
    private static final HttpClient HTTP = HttpClient.newHttpClient();
    private static final SecureRandom RANDOM = new SecureRandom();
    public static final String LAYER = "services";
    public static final String TITLE = "KuberCloud ANI Services API";
    public static final String VERSION = "1.0.0";
    public static final String SERVER_URL = "https://{host}/api/v1/svc";
    public static final List<String> OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "listGpuContainers",
        "createGpuContainer",
        "listAvailableGpus",
        "deleteGpuContainer",
        "getGpuContainer",
        "patchGpuContainer",
        "getGpuContainerMetrics",
        "rebuildGpuContainer",
        "rollbackGpuContainer",
        "listGpuContainerVersions",
        "getInferenceOperation",
        "listInferenceServices",
        "createInferenceService",
        "deleteInferenceService",
        "getInferenceService",
        "updateInferenceService",
        "applyInferenceServiceLifecycle",
        "getInferenceServiceLogs",
        "updateInferenceServicePolicies",
        "testInferenceService",
        "listIntegrations",
        "createIntegration",
        "createIntegrationBot",
        "listKnowledgeBases",
        "createKnowledgeBase",
        "deleteKnowledgeBase",
        "getKnowledgeBase",
        "listKnowledgeBaseCitations",
        "getKnowledgeBaseConfig",
        "updateKnowledgeBaseConfig",
        "listKnowledgeBaseDocuments",
        "getDocumentUploadURL",
        "deleteKnowledgeBaseDocument",
        "notifyDocumentUploaded",
        "reparseKnowledgeBaseDocument",
        "listKnowledgeBaseModels",
        "updateKnowledgeBasePermissions",
        "queryKnowledgeBase",
        "streamQueryKnowledgeBase",
        "rebuildKnowledgeBase",
        "listKnowledgeBaseSessions",
        "listModels",
        "createModel",
        "importModel",
        "deleteModel",
        "getModel",
        "createModelVersion",
        "listSandboxes",
        "createSandbox",
        "deleteSandbox",
        "getSandbox",
        "patchSandbox",
        "extendSandbox",
        "pauseSandbox",
        "listSandboxSecurityEvents",
        "getSandboxSecurityOverview",
        "listAllTenantAdmins",
        "listTenantPlans",
        "createTenantPlan",
        "deleteTenantPlan",
        "getTenantPlan",
        "activateTenantPlan",
        "listTenantPlanAuditLogs",
        "disableTenantPlan",
        "getTenantPlanQuotaLimits",
        "updateTenantPlanQuotaLimits",
        "listTenantPlanBoundTenants",
        "listTenantMembers",
        "inviteTenantMember",
        "removeTenantMember",
        "getTenantMember",
        "listTenantRoles",
        "updateTenantRole",
        "getSsoConfig",
        "updateSsoConfig",
        "listWebhooks",
        "createWebhook",
        "deleteWebhook",
        "listWebhookDeliveries",
        "inviteTenantAdmin",
        "deleteTenantAdmin",
        "getTenantAdminDetail",
        "listTenantAdminAuditLogs",
        "disableTenantAdmin",
        "enableTenantAdmin",
        "resendTenantAdminInvitation",
        "resetTenantAdminPassword",
        "getTenantAdminRole",
        "updateTenantAdminRole",
        "bindTenantPlan",
        "transferTenantOwnership"
    ));
    public static final List<String> PATHS = Collections.unmodifiableList(Arrays.asList(
        "GET /gpu-containers",
        "POST /gpu-containers",
        "GET /gpu-containers/available-gpus",
        "DELETE /gpu-containers/{container_id}",
        "GET /gpu-containers/{container_id}",
        "PATCH /gpu-containers/{container_id}",
        "GET /gpu-containers/{container_id}/metrics",
        "POST /gpu-containers/{container_id}/rebuild",
        "POST /gpu-containers/{container_id}/rollback",
        "GET /gpu-containers/{container_id}/versions",
        "GET /inference-operations/{operation_id}",
        "GET /inference-services",
        "POST /inference-services",
        "DELETE /inference-services/{service_id}",
        "GET /inference-services/{service_id}",
        "PATCH /inference-services/{service_id}",
        "POST /inference-services/{service_id}/lifecycle",
        "GET /inference-services/{service_id}/logs",
        "PUT /inference-services/{service_id}/policies",
        "POST /inference-services/{service_id}/test",
        "GET /integrations",
        "POST /integrations",
        "POST /integrations/bots",
        "GET /knowledge-bases",
        "POST /knowledge-bases",
        "DELETE /knowledge-bases/{kb_id}",
        "GET /knowledge-bases/{kb_id}",
        "GET /knowledge-bases/{kb_id}/citations",
        "GET /knowledge-bases/{kb_id}/config",
        "PUT /knowledge-bases/{kb_id}/config",
        "GET /knowledge-bases/{kb_id}/documents",
        "POST /knowledge-bases/{kb_id}/documents",
        "DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
        "POST /knowledge-bases/{kb_id}/documents/{doc_id}/notify-uploaded",
        "POST /knowledge-bases/{kb_id}/documents/{doc_id}/reparse",
        "GET /knowledge-bases/{kb_id}/models",
        "PUT /knowledge-bases/{kb_id}/permissions",
        "POST /knowledge-bases/{kb_id}/query",
        "GET /knowledge-bases/{kb_id}/query/stream",
        "POST /knowledge-bases/{kb_id}/rebuild",
        "GET /knowledge-bases/{kb_id}/sessions",
        "GET /models",
        "POST /models",
        "POST /models/import",
        "DELETE /models/{model_id}",
        "GET /models/{model_id}",
        "POST /models/{model_id}/versions",
        "GET /sandboxes",
        "POST /sandboxes",
        "DELETE /sandboxes/{sandbox_id}",
        "GET /sandboxes/{sandbox_id}",
        "PATCH /sandboxes/{sandbox_id}",
        "POST /sandboxes/{sandbox_id}/extend",
        "POST /sandboxes/{sandbox_id}/pause",
        "GET /sandboxes/{sandbox_id}/security-events",
        "GET /sandboxes/{sandbox_id}/security-overview",
        "GET /tenant-admins",
        "GET /tenant-plans",
        "POST /tenant-plans",
        "DELETE /tenant-plans/{planId}",
        "GET /tenant-plans/{planId}",
        "POST /tenant-plans/{planId}/activate",
        "GET /tenant-plans/{planId}/audit-logs",
        "POST /tenant-plans/{planId}/disable",
        "GET /tenant-plans/{planId}/quota-limits",
        "PUT /tenant-plans/{planId}/quota-limits",
        "GET /tenant-plans/{planId}/tenants",
        "GET /tenant/members",
        "POST /tenant/members",
        "DELETE /tenant/members/{member_id}",
        "GET /tenant/members/{member_id}",
        "GET /tenant/roles",
        "PUT /tenant/roles/{role_id}",
        "GET /tenant/sso",
        "PUT /tenant/sso",
        "GET /tenant/webhooks",
        "POST /tenant/webhooks",
        "DELETE /tenant/webhooks/{webhook_id}",
        "GET /tenant/webhooks/{webhook_id}/deliveries",
        "POST /tenants/{tenantId}/admins/invite",
        "DELETE /tenants/{tenantId}/admins/{userId}",
        "GET /tenants/{tenantId}/admins/{userId}",
        "GET /tenants/{tenantId}/admins/{userId}/audit-logs",
        "POST /tenants/{tenantId}/admins/{userId}/disable",
        "POST /tenants/{tenantId}/admins/{userId}/enable",
        "POST /tenants/{tenantId}/admins/{userId}/invitation/resend",
        "POST /tenants/{tenantId}/admins/{userId}/reset-password",
        "GET /tenants/{tenantId}/admins/{userId}/role",
        "PUT /tenants/{tenantId}/admins/{userId}/role",
        "POST /tenants/{tenantId}/plan",
        "POST /tenants/{tenantId}/transfer-ownership"
    ));
    public static final List<String> SCHEMAS = Collections.unmodifiableList(Arrays.asList(
        "AdminDetail",
        "AdminListResponse",
        "AdminWithTenant",
        "AsyncTask",
        "AvailableGpu",
        "BindPlanRequest",
        "BoundTenant",
        "BoundTenantsResponse",
        "CreateGpuContainerRequest",
        "CreateInferenceEndpointRequest",
        "CreateInferenceServiceRequest",
        "CreateIntegrationBotRequest",
        "CreateIntegrationRequest",
        "CreateModelRequest",
        "CreateSandboxRequest",
        "CreateTenantPlanRequest",
        "CreateWebhookRequest",
        "CursorPage",
        "ErrorResponse",
        "ExtendSandboxRequest",
        "GetDocumentUploadURLRequest",
        "GetDocumentUploadURLResponse",
        "GpuContainer",
        "GpuContainerMetrics",
        "GpuContainerVersion",
        "IdempotentOnlyRequest",
        "IdempotentResult",
        "InferenceEndpoint",
        "InferenceService",
        "InferenceServiceAccelerator",
        "InferenceServiceEngine",
        "InferenceServiceEngineEnvVar",
        "InferenceServiceLifecycleRequest",
        "InferenceServiceLogEntry",
        "InferenceServiceLogListResponse",
        "InferenceServicePolicies",
        "InferenceServiceResources",
        "InferenceTestRequest",
        "InferenceTestResponse",
        "Integration",
        "IntegrationBot",
        "IntegrationListResponse",
        "InvitationResult",
        "InviteAdminRequest",
        "InviteMemberRequest",
        "KBCitation",
        "KBCitationListResponse",
        "KBConfig",
        "KBDocument",
        "KBQueryRequest",
        "KBQueryResponse",
        "KBSession",
        "KBSessionListResponse",
        "KnowledgeBase",
        "Model",
        "ModelList",
        "ModelVersion",
        "NotifyDocumentUploadedRequest",
        "PatchGpuContainerRequest",
        "PatchSandboxRequest",
        "PlanAuditLog",
        "PlanAuditLogListResponse",
        "PlanQuotaLimitInput",
        "PlanQuotaLimitView",
        "PlanQuotaLimitsResponse",
        "RebuildKnowledgeBaseRequest",
        "ReparseDocumentRequest",
        "ResendInvitationRequest",
        "ResetPasswordRequest",
        "Sandbox",
        "SecurityEvent",
        "SecurityOverview",
        "SsoConfig",
        "TenantAdminAuditLog",
        "TenantAdminAuditLogListResponse",
        "TenantMember",
        "TenantPlan",
        "TenantPlanListItem",
        "TenantPlanListResponse",
        "TenantRef",
        "TenantRole",
        "TransferOwnershipRequest",
        "UpdateInferenceServicePoliciesRequest",
        "UpdateInferenceServiceRequest",
        "UpdateKBConfigRequest",
        "UpdateKBPermissionsRequest",
        "UpdateQuotaLimitsRequest",
        "UpdateRoleRequest",
        "UpdateSsoConfigRequest",
        "UpdateTenantRoleRequest",
        "UserPermissions",
        "Webhook",
        "WebhookDelivery",
        "WebhookDeliveryListResponse"
    ));
    public static final List<String> IDEMPOTENCY_OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "createGpuContainer",
        "patchGpuContainer",
        "createInferenceService",
        "updateInferenceService",
        "applyInferenceServiceLifecycle",
        "updateInferenceServicePolicies",
        "testInferenceService",
        "createIntegration",
        "createIntegrationBot",
        "updateKnowledgeBaseConfig",
        "getDocumentUploadURL",
        "notifyDocumentUploaded",
        "reparseKnowledgeBaseDocument",
        "updateKnowledgeBasePermissions",
        "queryKnowledgeBase",
        "rebuildKnowledgeBase",
        "createSandbox",
        "patchSandbox",
        "extendSandbox",
        "createTenantPlan",
        "updateTenantPlanQuotaLimits",
        "inviteTenantMember",
        "updateTenantRole",
        "updateSsoConfig",
        "createWebhook",
        "inviteTenantAdmin",
        "disableTenantAdmin",
        "enableTenantAdmin",
        "resendTenantAdminInvitation",
        "resetTenantAdminPassword",
        "updateTenantAdminRole",
        "bindTenantPlan",
        "transferTenantOwnership"
    ));
    public static final List<String> CURSOR_PAGINATION_OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "listGpuContainers",
        "getInferenceServiceLogs",
        "listIntegrations",
        "listKnowledgeBaseCitations",
        "listKnowledgeBaseSessions",
        "listModels",
        "listSandboxes",
        "listAllTenantAdmins",
        "listTenantPlans",
        "listTenantPlanAuditLogs",
        "listWebhookDeliveries",
        "listTenantAdminAuditLogs"
    ));
    public static final List<String> ERROR_CODES = Collections.unmodifiableList(Arrays.asList(
        "ACCELERATOR_SPEC_UNAVAILABLE",
        "BAD_REQUEST",
        "CONFLICT",
        "DEPENDENCY_UNAVAILABLE",
        "FEATURE_NOT_AVAILABLE",
        "FORBIDDEN",
        "IDEMPOTENCY_CONFLICT",
        "IMAGE_UNAVAILABLE",
        "INSUFFICIENT_CAPACITY",
        "INVALID_ARGUMENT",
        "INVALID_STATE_TRANSITION",
        "MODEL_INCOMPATIBLE",
        "MODEL_NOT_READY",
        "NAME_CONFLICT",
        "NOT_FOUND",
        "OPERATION_IN_PROGRESS",
        "PRECONDITION_FAILED",
        "RUNTIME_ERROR",
        "RUNTIME_TIMEOUT",
        "UNAUTHORIZED",
        "UNSUPPORTED_TOPOLOGY"
    ));

    private final String baseUrl;
    private final String token;

    public static final class APIError {
        private final String code;
        private final String message;
        private final String requestId;
        private final Map<String, Object> details;

        public APIError(String code, String message, String requestId, Map<String, Object> details) {
            this.code = code;
            this.message = message;
            this.requestId = requestId;
            this.details = details == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(details));
        }

        public String code() {
            return code;
        }

        public String message() {
            return message;
        }

        public String requestId() {
            return requestId;
        }

        public Map<String, Object> details() {
            return details;
        }
    }

    public static final class APIException extends Exception {
        private final APIError apiError;

        public APIException(APIError apiError) {
            super(apiError == null ? "" : apiError.code() + ": " + apiError.message());
            this.apiError = apiError;
        }

        public APIError apiError() {
            return apiError;
        }
    }

    public static final class RequestOptions {
        private final String bodyJson;
        private final Map<String, String> params;
        private final Map<String, String> headers;

        public RequestOptions(String bodyJson, Map<String, String> params, Map<String, String> headers) {
            this.bodyJson = bodyJson;
            this.params = params == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(params));
            this.headers = headers == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(headers));
        }

        public String bodyJson() {
            return bodyJson;
        }

        public Map<String, String> params() {
            return params;
        }

        public Map<String, String> headers() {
            return headers;
        }
    }

    public ApiClient(String baseUrl, String token) {
        this.baseUrl = (baseUrl == null || baseUrl.isEmpty()) ? SERVER_URL : baseUrl;
        this.token = token;
    }

    public String baseUrl() {
        return baseUrl;
    }

    public String token() {
        return token;
    }

    public boolean hasOperation(String operationId) {
        return OPERATIONS.contains(operationId);
    }

    public String request(String method, String path, RequestOptions options) throws IOException, InterruptedException, APIException {
        RequestOptions opts = options == null ? new RequestOptions(null, null, null) : options;
        HttpRequest.Builder builder = HttpRequest.newBuilder(URI.create(requestUrl(path, opts.params())))
                .header("Accept", "application/json");
        if (token != null && !token.isEmpty()) {
            builder.header("Authorization", "Bearer " + token);
        }
        for (Map.Entry<String, String> entry : opts.headers().entrySet()) {
            builder.header(entry.getKey(), entry.getValue());
        }
        String upperMethod = method == null ? "GET" : method.toUpperCase();
        if (opts.bodyJson() == null) {
            builder.method(upperMethod, HttpRequest.BodyPublishers.noBody());
        } else {
            builder.header("Content-Type", "application/json");
            builder.method(upperMethod, HttpRequest.BodyPublishers.ofString(opts.bodyJson()));
        }
        HttpResponse<String> response = HTTP.send(builder.build(), HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() >= 400) {
            throw new APIException(parseAPIError(response.body(), response.statusCode()));
        }
        return response.body();
    }

    private String requestUrl(String path, Map<String, String> params) {
        String base = baseUrl.replaceAll("/+$", "");
        String relative = path == null || path.isEmpty() ? "/" : "/" + path.replaceAll("^/+", "");
        if (params == null || params.isEmpty()) {
            return base + relative;
        }
        StringJoiner query = new StringJoiner("&");
        for (Map.Entry<String, String> entry : params.entrySet()) {
            if (entry.getValue() != null && !entry.getValue().isEmpty()) {
                query.add(URLEncoder.encode(entry.getKey(), StandardCharsets.UTF_8) + "=" + URLEncoder.encode(entry.getValue(), StandardCharsets.UTF_8));
            }
        }
        String encoded = query.toString();
        return encoded.isEmpty() ? base + relative : base + relative + "?" + encoded;
    }

    private static APIError parseAPIError(String body, int statusCode) {
        String code = jsonString(body, "code");
        String message = jsonString(body, "message");
        String requestId = jsonString(body, "request_id");
        if (code == null || code.isEmpty()) {
            code = "HTTP_" + statusCode;
        }
        if (message == null || message.isEmpty()) {
            message = "ANI API request failed";
        }
        return new APIError(code, message, requestId == null ? "" : requestId, null);
    }

    private static String jsonString(String body, String field) {
        if (body == null) {
            return "";
        }
        Pattern pattern = Pattern.compile("\\\"" + Pattern.quote(field) + "\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"");
        Matcher matcher = pattern.matcher(body);
        return matcher.find() ? matcher.group(1) : "";
    }

    public static String newIdempotencyKey(String prefix) {
        String safePrefix = (prefix == null || prefix.isEmpty()) ? "ani" : prefix;
        byte[] random = new byte[16];
        RANDOM.nextBytes(random);
        StringBuilder encoded = new StringBuilder(random.length * 2);
        for (byte value : random) {
            encoded.append(String.format("%02x", value & 0xff));
        }
        return safePrefix + "_" + encoded;
    }

    public static Map<String, Object> withIdempotencyKey(Map<String, Object> body, String key) {
        Map<String, Object> payload = new HashMap<>();
        if (body != null) {
            payload.putAll(body);
        }
        payload.put("idempotency_key", (key == null || key.isEmpty()) ? newIdempotencyKey("ani") : key);
        return payload;
    }

    public static Map<String, String> cursorParams(int limit, String cursor) {
        Map<String, String> params = new HashMap<>();
        if (limit > 0) {
            params.put("limit", Integer.toString(limit));
        }
        if (cursor != null && !cursor.isEmpty()) {
            params.put("cursor", cursor);
        }
        return params;
    }

    public static boolean isAPIErrorCode(String code) {
        return ERROR_CODES.contains(code);
    }

    public static APIError apiError(String code, String message, String requestId, Map<String, Object> details) {
        return new APIError(code, message, requestId, details);
    }
}
