// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package com.kubercloud.ani.core;

import java.security.SecureRandom;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class ApiClient {
    private static final HttpClient HTTP = HttpClient.newHttpClient();
    private static final SecureRandom RANDOM = new SecureRandom();
    public static final String LAYER = "core";
    public static final String TITLE = "KuberCloud ANI Core API";
    public static final String VERSION = "1.0.0";
    public static final String SERVER_URL = "https://{host}/api/v1";
    public static final List<String> OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "listQuotaMeta",
        "deleteTenantQuota",
        "getTenantQuota",
        "createTenantQuota",
        "updateTenantQuota",
        "upsertTenantQuota",
        "getTenantReservations",
        "putTenantReservations",
        "listAPIKeys",
        "createAPIKey",
        "revokeAPIKey",
        "logout",
        "beginOIDCLogin",
        "passwordLogin",
        "platformPasswordLogin",
        "postAuthRefresh",
        "completeOIDCLogin",
        "getBranding",
        "listStorageBuckets",
        "createStorageBucket",
        "setStorageBucketACL",
        "listStorageBucketLifecycleRules",
        "createStorageBucketLifecycleRule",
        "setStorageBucketLifecycleRules",
        "deleteStorageBucketLifecycleRule",
        "deleteBucketObject",
        "listBucketObjects",
        "generateBucketObjectPresignedURL",
        "uploadBucketObject",
        "createBucketPrefix",
        "setStorageBucketClass",
        "listEncryptionKeys",
        "createEncryptionKey",
        "deleteEncryptionKey",
        "getEncryptionKey",
        "revokeEncryptionKey",
        "rotateEncryptionKey",
        "sealEncryptionObject",
        "createEncryptionUnsealToken",
        "listStorageFilesystems",
        "createStorageFilesystem",
        "deleteStorageFilesystem",
        "getStorageFilesystem",
        "expandStorageFilesystem",
        "mountStorageFilesystem",
        "getFilesystemMountCommand",
        "listFilesystemMountTargets",
        "createFilesystemMountTarget",
        "unmountStorageFilesystem",
        "listGPUInventory",
        "getGPUOccupancy",
        "updateGPUDeviceStatus",
        "listGPUSchedulingQueues",
        "createGPUSchedulingQueue",
        "deleteGPUSchedulingQueue",
        "getGPUSchedulingQueue",
        "updateGPUSchedulingQueue",
        "listGPUSpecs",
        "createGPUSpec",
        "listGPUSpecAvailability",
        "deleteGPUSpec",
        "getGPUSpec",
        "liveness",
        "getInstanceOperation",
        "listInstances",
        "createInstance",
        "getInstance",
        "createInstanceConsoleSession",
        "listInstanceEvents",
        "createInstanceExecSession",
        "applyInstanceLifecycle",
        "listInstanceLogs",
        "getInstanceMetrics",
        "listInstanceOperations",
        "listSandboxCheckpoints",
        "createSandboxCheckpoint",
        "cloneSandboxCheckpoint",
        "restoreSandboxCheckpoint",
        "createSandboxCodeRun",
        "deleteSandboxFile",
        "listSandboxFiles",
        "writeSandboxFile",
        "createSandboxPort",
        "deleteSandboxPort",
        "createSandboxToken",
        "listInstanceSecurityEvents",
        "listK8sClusters",
        "createK8sCluster",
        "deleteK8sCluster",
        "getK8sCluster",
        "getK8sClusterKubeconfig",
        "listK8sClusterNodePools",
        "createK8sClusterNodePool",
        "deleteK8sClusterNodePool",
        "getK8sClusterNodePool",
        "updateK8sClusterNodePool",
        "proxyK8sClusterAPI",
        "upgradeK8sCluster",
        "listK8sClusterWorkloads",
        "reportTokenUsage",
        "getMeteringUsage",
        "getPlatformMeteringUsage",
        "listNetworkLoadBalancers",
        "createNetworkLoadBalancer",
        "deleteNetworkLoadBalancer",
        "getNetworkLoadBalancer",
        "getNetworkOverview",
        "listNetworkRoutes",
        "createNetworkRoute",
        "deleteNetworkRoute",
        "getNetworkRoute",
        "listNetworkSecurityGroups",
        "createNetworkSecurityGroup",
        "deleteNetworkSecurityGroup",
        "getNetworkSecurityGroup",
        "listNetworkSecurityGroupBindings",
        "createNetworkSecurityGroupBinding",
        "deleteNetworkSecurityGroupBinding",
        "listNetworkSecurityGroupRules",
        "createNetworkSecurityGroupRule",
        "deleteNetworkSecurityGroupRule",
        "getNetworkSecurityGroupRule",
        "updateNetworkSecurityGroupRule",
        "listNetworkSubnets",
        "createNetworkSubnet",
        "deleteNetworkSubnet",
        "getNetworkSubnet",
        "listNetworkSubnetIPAllocations",
        "listNetworkVPCs",
        "createNetworkVPC",
        "deleteNetworkVPC",
        "getNetworkVPC",
        "listEmailRecipients",
        "createEmailRecipient",
        "deleteEmailRecipient",
        "updateEmailRecipient",
        "getEmailSmtpConfig",
        "putEmailSmtpConfig",
        "listEmailSubscriptions",
        "putEmailSubscriptions",
        "sendTestEmail",
        "listStorageObjects",
        "createStorageObject",
        "uploadStorageObject",
        "deleteStorageObject",
        "getStorageObject",
        "downloadStorageObject",
        "listObservabilityAlertRules",
        "createObservabilityAlertRule",
        "deleteObservabilityAlertRule",
        "getObservabilityAlertRule",
        "updateObservabilityAlertRule",
        "queryObservability",
        "queryRangeObservability",
        "getPlatformWorkloadCapabilities",
        "createPlatformWorkload",
        "deletePlatformWorkload",
        "getPlatformWorkload",
        "updatePlatformWorkload",
        "applyPlatformWorkloadLifecycle",
        "getPlatformWorkloadLogs",
        "listQuotas",
        "getMyQuota",
        "readiness",
        "listRegistryImages",
        "getRegistryImageScanResult",
        "getRegistryOverview",
        "listRegistryProjects",
        "createRegistryProject",
        "createRegistryProjectPullSecret",
        "getRegistryProjectPushInstructions",
        "listRegistryRepositories",
        "listRegistryArtifacts",
        "setRegistryRepositoryPermission",
        "deleteRegistryRepositoryTag",
        "listRegistryRepositoryTagReferences",
        "getRegistryProjectScanReport",
        "getMyReservations",
        "listSandboxTemplates",
        "listSecrets",
        "createSecret",
        "deleteSecret",
        "getSecret",
        "bindSecret",
        "getTasksTaskId",
        "listVectorStores",
        "createVectorStore",
        "deleteVectorStore",
        "getVectorStore",
        "precheckVectorStoreDelete",
        "deleteVectorStoreDocuments",
        "insertVectorStoreDocuments",
        "deleteVectorStoreKnowledgeBaseLink",
        "setVectorStoreKnowledgeBaseLink",
        "rebuildVectorStoreIndex",
        "searchVectorStore",
        "listStorageVolumes",
        "createStorageVolume",
        "deleteStorageVolume",
        "getStorageVolume",
        "setVolumeAutoSnapshotPolicy",
        "expandStorageVolume",
        "mountStorageVolume",
        "completeVolumeOSInit",
        "getVolumeOSInitGuide",
        "listVolumeSnapshots",
        "createVolumeSnapshot",
        "createStorageVolumeFromSnapshot",
        "unmountStorageVolume"
    ));
    public static final List<String> PATHS = Collections.unmodifiableList(Arrays.asList(
        "GET /admin/quota-meta",
        "DELETE /admin/tenants/{tenant_id}/quota",
        "GET /admin/tenants/{tenant_id}/quota",
        "POST /admin/tenants/{tenant_id}/quota",
        "PUT /admin/tenants/{tenant_id}/quota",
        "PUT /admin/tenants/{tenant_id}/quota/upsert",
        "GET /admin/tenants/{tenant_id}/reservations",
        "PUT /admin/tenants/{tenant_id}/reservations",
        "GET /auth/api-keys",
        "POST /auth/api-keys",
        "DELETE /auth/api-keys/{key_id}",
        "POST /auth/logout",
        "POST /auth/oidc/begin",
        "POST /auth/password/login",
        "POST /auth/platform/password/login",
        "POST /auth/refresh",
        "POST /auth/token",
        "GET /branding",
        "GET /buckets",
        "POST /buckets",
        "PUT /buckets/{bucket_id}/acl",
        "GET /buckets/{bucket_id}/lifecycle-rules",
        "POST /buckets/{bucket_id}/lifecycle-rules",
        "PUT /buckets/{bucket_id}/lifecycle-rules",
        "DELETE /buckets/{bucket_id}/lifecycle-rules/{rule_id}",
        "DELETE /buckets/{bucket_id}/objects",
        "GET /buckets/{bucket_id}/objects",
        "POST /buckets/{bucket_id}/objects/presigned-url",
        "POST /buckets/{bucket_id}/objects/upload",
        "POST /buckets/{bucket_id}/prefixes",
        "PUT /buckets/{bucket_id}/storage-class",
        "GET /encryption/keys",
        "POST /encryption/keys",
        "DELETE /encryption/keys/{key_id}",
        "GET /encryption/keys/{key_id}",
        "POST /encryption/keys/{key_id}/revoke",
        "POST /encryption/keys/{key_id}/rotate",
        "POST /encryption/seal",
        "POST /encryption/unseal-token",
        "GET /filesystems",
        "POST /filesystems",
        "DELETE /filesystems/{filesystem_id}",
        "GET /filesystems/{filesystem_id}",
        "POST /filesystems/{filesystem_id}/expand",
        "POST /filesystems/{filesystem_id}/mount",
        "GET /filesystems/{filesystem_id}/mount-command",
        "GET /filesystems/{filesystem_id}/mount-targets",
        "POST /filesystems/{filesystem_id}/mount-targets",
        "POST /filesystems/{filesystem_id}/unmount",
        "GET /gpu-inventory",
        "GET /gpu-inventory/occupancy",
        "PATCH /gpu-inventory/{device_id}",
        "GET /gpu-scheduling/queues",
        "POST /gpu-scheduling/queues",
        "DELETE /gpu-scheduling/queues/{queue_id}",
        "GET /gpu-scheduling/queues/{queue_id}",
        "PATCH /gpu-scheduling/queues/{queue_id}",
        "GET /gpu-specs",
        "POST /gpu-specs",
        "GET /gpu-specs/availability",
        "DELETE /gpu-specs/{spec_id}",
        "GET /gpu-specs/{spec_id}",
        "GET /healthz",
        "GET /instance-operations/{operation_id}",
        "GET /instances",
        "POST /instances",
        "GET /instances/{instance_id}",
        "POST /instances/{instance_id}/console",
        "GET /instances/{instance_id}/events",
        "POST /instances/{instance_id}/exec",
        "POST /instances/{instance_id}/lifecycle",
        "GET /instances/{instance_id}/logs",
        "GET /instances/{instance_id}/metrics",
        "GET /instances/{instance_id}/operations",
        "GET /instances/{instance_id}/sandbox/checkpoints",
        "POST /instances/{instance_id}/sandbox/checkpoints",
        "POST /instances/{instance_id}/sandbox/checkpoints/{checkpoint_id}/clone",
        "POST /instances/{instance_id}/sandbox/checkpoints/{checkpoint_id}/restore",
        "POST /instances/{instance_id}/sandbox/code-runs",
        "DELETE /instances/{instance_id}/sandbox/files",
        "GET /instances/{instance_id}/sandbox/files",
        "POST /instances/{instance_id}/sandbox/files",
        "POST /instances/{instance_id}/sandbox/ports",
        "DELETE /instances/{instance_id}/sandbox/ports/{port}",
        "POST /instances/{instance_id}/sandbox/tokens",
        "GET /instances/{instance_id}/security-events",
        "GET /k8s-clusters",
        "POST /k8s-clusters",
        "DELETE /k8s-clusters/{cluster_id}",
        "GET /k8s-clusters/{cluster_id}",
        "GET /k8s-clusters/{cluster_id}/kubeconfig",
        "GET /k8s-clusters/{cluster_id}/node-pools",
        "POST /k8s-clusters/{cluster_id}/node-pools",
        "DELETE /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
        "GET /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
        "PATCH /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
        "POST /k8s-clusters/{cluster_id}/proxy",
        "POST /k8s-clusters/{cluster_id}/upgrade",
        "GET /k8s-clusters/{cluster_id}/workloads",
        "POST /metering/token-usage",
        "GET /metering/usage",
        "GET /metering/usage/platform",
        "GET /networks/load-balancers",
        "POST /networks/load-balancers",
        "DELETE /networks/load-balancers/{load_balancer_id}",
        "GET /networks/load-balancers/{load_balancer_id}",
        "GET /networks/overview",
        "GET /networks/routes",
        "POST /networks/routes",
        "DELETE /networks/routes/{route_id}",
        "GET /networks/routes/{route_id}",
        "GET /networks/security-groups",
        "POST /networks/security-groups",
        "DELETE /networks/security-groups/{security_group_id}",
        "GET /networks/security-groups/{security_group_id}",
        "GET /networks/security-groups/{security_group_id}/bindings",
        "POST /networks/security-groups/{security_group_id}/bindings",
        "DELETE /networks/security-groups/{security_group_id}/bindings/{binding_id}",
        "GET /networks/security-groups/{security_group_id}/rules",
        "POST /networks/security-groups/{security_group_id}/rules",
        "DELETE /networks/security-groups/{security_group_id}/rules/{rule_id}",
        "GET /networks/security-groups/{security_group_id}/rules/{rule_id}",
        "PUT /networks/security-groups/{security_group_id}/rules/{rule_id}",
        "GET /networks/subnets",
        "POST /networks/subnets",
        "DELETE /networks/subnets/{subnet_id}",
        "GET /networks/subnets/{subnet_id}",
        "GET /networks/subnets/{subnet_id}/ip-allocations",
        "GET /networks/vpcs",
        "POST /networks/vpcs",
        "DELETE /networks/vpcs/{vpc_id}",
        "GET /networks/vpcs/{vpc_id}",
        "GET /notifications/email/recipients",
        "POST /notifications/email/recipients",
        "DELETE /notifications/email/recipients/{recipient_id}",
        "PATCH /notifications/email/recipients/{recipient_id}",
        "GET /notifications/email/smtp",
        "PUT /notifications/email/smtp",
        "GET /notifications/email/subscriptions",
        "PUT /notifications/email/subscriptions",
        "POST /notifications/email/test",
        "GET /objects",
        "POST /objects",
        "POST /objects/upload",
        "DELETE /objects/{object_id}",
        "GET /objects/{object_id}",
        "GET /objects/{object_id}/download",
        "GET /observability/alert-rules",
        "POST /observability/alert-rules",
        "DELETE /observability/alert-rules/{rule_id}",
        "GET /observability/alert-rules/{rule_id}",
        "PATCH /observability/alert-rules/{rule_id}",
        "GET /observability/query",
        "GET /observability/query_range",
        "GET /platform-workload-capabilities",
        "POST /platform-workloads",
        "DELETE /platform-workloads/{workload_id}",
        "GET /platform-workloads/{workload_id}",
        "PATCH /platform-workloads/{workload_id}",
        "POST /platform-workloads/{workload_id}/lifecycle",
        "GET /platform-workloads/{workload_id}/logs",
        "GET /quotas",
        "GET /quotas/me",
        "GET /readyz",
        "GET /registry/images",
        "GET /registry/images/scan-result",
        "GET /registry/overview",
        "GET /registry/projects",
        "POST /registry/projects",
        "POST /registry/projects/{project}/pull-secret",
        "GET /registry/projects/{project}/push-instructions",
        "GET /registry/projects/{project}/repositories",
        "GET /registry/projects/{project}/repositories/{repository}/artifacts",
        "POST /registry/projects/{project}/repositories/{repository}/permissions",
        "DELETE /registry/projects/{project}/repositories/{repository}/tags/{tag}",
        "GET /registry/projects/{project}/repositories/{repository}/tags/{tag}/references",
        "GET /registry/projects/{project}/scan-report",
        "GET /reservations/me",
        "GET /sandbox-templates",
        "GET /secrets",
        "POST /secrets",
        "DELETE /secrets/{secret_id}",
        "GET /secrets/{secret_id}",
        "POST /secrets/{secret_id}/bindings",
        "GET /tasks/{task_id}",
        "GET /vector-stores",
        "POST /vector-stores",
        "DELETE /vector-stores/{vector_store_id}",
        "GET /vector-stores/{vector_store_id}",
        "GET /vector-stores/{vector_store_id}/delete-precheck",
        "DELETE /vector-stores/{vector_store_id}/documents",
        "POST /vector-stores/{vector_store_id}/documents",
        "DELETE /vector-stores/{vector_store_id}/knowledge-base-link",
        "PUT /vector-stores/{vector_store_id}/knowledge-base-link",
        "POST /vector-stores/{vector_store_id}/rebuild-index",
        "POST /vector-stores/{vector_store_id}/search",
        "GET /volumes",
        "POST /volumes",
        "DELETE /volumes/{volume_id}",
        "GET /volumes/{volume_id}",
        "PUT /volumes/{volume_id}/auto-snapshot-policy",
        "POST /volumes/{volume_id}/expand",
        "POST /volumes/{volume_id}/mount",
        "POST /volumes/{volume_id}/os-init-complete",
        "GET /volumes/{volume_id}/os-init-guide",
        "GET /volumes/{volume_id}/snapshots",
        "POST /volumes/{volume_id}/snapshots",
        "POST /volumes/{volume_id}/snapshots/{snapshot_id}/create-volume",
        "POST /volumes/{volume_id}/unmount"
    ));
    public static final List<String> SCHEMAS = Collections.unmodifiableList(Arrays.asList(
        "APIKeyInfo",
        "AsyncTask",
        "BeginOIDCLoginRequest",
        "BeginOIDCLoginResponse",
        "BucketObjectDeleteResponse",
        "BucketObjectPresignedURLRequest",
        "BucketObjectUploadRequest",
        "BucketPrefixCreateRequest",
        "CloneSandboxCheckpointRequest",
        "CompleteOIDCLoginRequest",
        "CoreDevProfileInfo",
        "CreateAPIKeyRequest",
        "CreateAPIKeyResponse",
        "CreateContainerInstanceConfig",
        "CreateEmailRecipientRequest",
        "CreateGPUContainerInstanceConfig",
        "CreateInstanceConsoleSessionRequest",
        "CreateInstanceExecSessionRequest",
        "CreateInstanceRequest",
        "CreateInstanceResponse",
        "CreateNetworkLoadBalancerRequest",
        "CreateNetworkRouteRequest",
        "CreateNetworkSecurityGroupBindingRequest",
        "CreateNetworkSecurityGroupRequest",
        "CreateNetworkSecurityGroupRuleRequest",
        "CreateNetworkSubnetRequest",
        "CreateNetworkVPCRequest",
        "CreateObservabilityAlertRuleRequest",
        "CreateRegistryProjectRequest",
        "CreateRegistryPullSecretRequest",
        "CreateSandboxCheckpointRequest",
        "CreateSandboxCodeRunRequest",
        "CreateSandboxPortRequest",
        "CreateSandboxTokenRequest",
        "CreateStorageBucketRequest",
        "CreateStorageFilesystemRequest",
        "CreateStorageObjectRequest",
        "CreateStorageVolumeFromSnapshotRequest",
        "CreateStorageVolumeRequest",
        "CreateVMInstanceConfig",
        "CreateVectorStoreRequest",
        "CreateVolumeSnapshotRequest",
        "CursorPage",
        "EmailRecipient",
        "EmailRecipientListResponse",
        "EmailSmtpConfigResponse",
        "EmailSubscription",
        "EmailSubscriptionListResponse",
        "EncryptionKey",
        "EncryptionKeyCreateRequest",
        "EncryptionKeyListResponse",
        "EncryptionKeyRevokeRequest",
        "EncryptionKeyRotateRequest",
        "EncryptionKeyRotationResponse",
        "EncryptionSealRequest",
        "EncryptionSealResponse",
        "EncryptionUnsealTokenRequest",
        "EncryptionUnsealTokenResponse",
        "ErrorResponse",
        "FilesystemAttachment",
        "FilesystemMountCommand",
        "FilesystemMountTarget",
        "FilesystemMountTargetCreateRequest",
        "FilesystemMountTargetListResponse",
        "GPUDeviceStatusUpdateRequest",
        "GPUInventoryListResponse",
        "GPUInventoryRecord",
        "GPUOccupancyStats",
        "GPUSchedulingQueue",
        "GPUSchedulingQueueCreateRequest",
        "GPUSchedulingQueueListResponse",
        "GPUSchedulingQueueUpdateRequest",
        "GPUSpec",
        "GPUSpecAvailability",
        "GPUSpecAvailabilityListResponse",
        "GPUSpecCreateRequest",
        "GPUSpecListResponse",
        "GPUSpecNodeAffinity",
        "GPUSpecSummary",
        "GPUSpecVolcanoResources",
        "HealthCheck",
        "InstanceAccessSummary",
        "InstanceComputeSummary",
        "InstanceConsoleSession",
        "InstanceDiskSpec",
        "InstanceEnvVar",
        "InstanceEvent",
        "InstanceEventListResponse",
        "InstanceExecSession",
        "InstanceFilesystemMount",
        "InstanceImageSummary",
        "InstanceLifecycleRequest",
        "InstanceLifecycleResponse",
        "InstanceListResponse",
        "InstanceLogEntry",
        "InstanceLogListResponse",
        "InstanceMetrics",
        "InstanceNetworkConfig",
        "InstanceNetworkSummary",
        "InstanceOperation",
        "InstancePortSpec",
        "InstanceRecord",
        "InstanceSecurityEvent",
        "InstanceSecurityEventListResponse",
        "InstanceStorageAttachment",
        "InstanceVolumeMount",
        "InstanceWorkloadIdentityConfig",
        "K8sCluster",
        "K8sClusterCreateRequest",
        "K8sClusterKubeconfig",
        "K8sClusterListResponse",
        "K8sClusterNodePool",
        "K8sClusterNodePoolCreateRequest",
        "K8sClusterNodePoolGPU",
        "K8sClusterNodePoolListResponse",
        "K8sClusterNodePoolUpdateRequest",
        "K8sClusterProxyRequest",
        "K8sClusterProxyResponse",
        "K8sClusterUpgradeRequest",
        "K8sClusterWorkload",
        "K8sClusterWorkloadListResponse",
        "ListAPIKeysResponse",
        "LogoutRequest",
        "MeteringUsageRecord",
        "MeteringUsageResponse",
        "NetworkLoadBalancer",
        "NetworkLoadBalancerListResponse",
        "NetworkLoadBalancerListener",
        "NetworkOverview",
        "NetworkOverviewCapability",
        "NetworkOverviewDeleteRisk",
        "NetworkOverviewRelationship",
        "NetworkOverviewResourceKind",
        "NetworkOverviewResourceSummary",
        "NetworkResourceState",
        "NetworkRoute",
        "NetworkRouteListResponse",
        "NetworkSecurityGroup",
        "NetworkSecurityGroupBinding",
        "NetworkSecurityGroupBindingListResponse",
        "NetworkSecurityGroupBindingTargetType",
        "NetworkSecurityGroupListResponse",
        "NetworkSecurityGroupRule",
        "NetworkSecurityGroupRuleListResponse",
        "NetworkSecurityGroupRuleResource",
        "NetworkSubnet",
        "NetworkSubnetIPAllocation",
        "NetworkSubnetIPAllocationListResponse",
        "NetworkSubnetListResponse",
        "NetworkVPC",
        "NetworkVPCListResponse",
        "ObservabilityAlertRule",
        "ObservabilityAlertRuleListResponse",
        "ObservabilityQueryResponse",
        "ObservabilityRangeQueryResponse",
        "PasswordLoginRequest",
        "PlatformPasswordLoginRequest",
        "PlatformWorkload",
        "PlatformWorkloadAcceleratorCapability",
        "PlatformWorkloadAcceleratorResources",
        "PlatformWorkloadArtifact",
        "PlatformWorkloadCapabilities",
        "PlatformWorkloadCreateRequest",
        "PlatformWorkloadHealthCheck",
        "PlatformWorkloadLifecycleRequest",
        "PlatformWorkloadLogEntry",
        "PlatformWorkloadLogListResponse",
        "PlatformWorkloadMetadata",
        "PlatformWorkloadNetwork",
        "PlatformWorkloadPort",
        "PlatformWorkloadResources",
        "PlatformWorkloadRole",
        "PlatformWorkloadScheduling",
        "PlatformWorkloadSecretBinding",
        "PlatformWorkloadTopology",
        "PlatformWorkloadUpdateRequest",
        "PutEmailSmtpConfigRequest",
        "PutEmailSubscriptionsRequest",
        "Quota",
        "QuotaCreateItem",
        "QuotaCreateRequest",
        "QuotaDeleteResponse",
        "QuotaItem",
        "QuotaListResult",
        "QuotaMeta",
        "QuotaMetaListResponse",
        "QuotaUpdateItem",
        "QuotaUpdateRequest",
        "QuotaUpsertItem",
        "QuotaUpsertRequest",
        "RefreshAccessTokenRequest",
        "RefreshAccessTokenResponse",
        "RegistryArtifact",
        "RegistryArtifactListResponse",
        "RegistryCommand",
        "RegistryDeletedTag",
        "RegistryImage",
        "RegistryImageListResponse",
        "RegistryImageReference",
        "RegistryImageReferenceListResponse",
        "RegistryOverview",
        "RegistryOverviewCapability",
        "RegistryOverviewDeleteRisk",
        "RegistryOverviewQuickAction",
        "RegistryOverviewRelationship",
        "RegistryOverviewResourceSummary",
        "RegistryOverviewVulnerabilitySummary",
        "RegistryPermission",
        "RegistryProject",
        "RegistryProjectListResponse",
        "RegistryProjectScanReport",
        "RegistryPullSecret",
        "RegistryPushInstructions",
        "RegistryRepository",
        "RegistryRepositoryListResponse",
        "RegistryScanResult",
        "ReportTokenUsageRequest",
        "ReservationPutRequest",
        "ReservationView",
        "RevokeStatusResponse",
        "SandboxCheckpoint",
        "SandboxCheckpointActionRequest",
        "SandboxCheckpointListResponse",
        "SandboxCodeRun",
        "SandboxConfig",
        "SandboxFile",
        "SandboxFileListResponse",
        "SandboxInstanceStatus",
        "SandboxNetworkEgressPolicy",
        "SandboxPort",
        "SandboxTemplate",
        "SandboxTemplateListResponse",
        "SandboxTokenResponse",
        "Secret",
        "SecretBinding",
        "SecretBindingRequest",
        "SecretCreateRequest",
        "SecretListResponse",
        "SendTestEmailResponse",
        "SetRegistryPermissionRequest",
        "StorageBucketACLUpdateRequest",
        "StorageBucketClassUpdateRequest",
        "StorageBucketLifecycleRule",
        "StorageBucketLifecycleRuleCreateRequest",
        "StorageBucketLifecycleRuleListResponse",
        "StorageBucketLifecycleRulesUpdateRequest",
        "StorageBucketListResponse",
        "StorageBucketObjectEntry",
        "StorageBucketObjectListResponse",
        "StorageBucketRecord",
        "StorageFilesystem",
        "StorageFilesystemExpandRequest",
        "StorageFilesystemListResponse",
        "StorageFilesystemMountRequest",
        "StorageFilesystemUnmountRequest",
        "StorageObject",
        "StorageObjectDownloadInfo",
        "StorageObjectListResponse",
        "StorageObjectUploadRequest",
        "StorageObjectUploadResponse",
        "StorageResourceState",
        "StorageVolume",
        "StorageVolumeAutoSnapshotPolicy",
        "StorageVolumeAutoSnapshotPolicyUpdateRequest",
        "StorageVolumeExpandRequest",
        "StorageVolumeListResponse",
        "StorageVolumeMountHistoryEntry",
        "StorageVolumeMountRequest",
        "StorageVolumeUnmountRequest",
        "TokenPairResponse",
        "TokenUsageReport",
        "UpdateEmailRecipientRequest",
        "UpdateNetworkSecurityGroupRuleRequest",
        "UpdateObservabilityAlertRuleRequest",
        "VectorStore",
        "VectorStoreDeletePrecheck",
        "VectorStoreDocumentDeleteResponse",
        "VectorStoreDocumentInsertRequest",
        "VectorStoreDocumentInsertResponse",
        "VectorStoreIndexStatus",
        "VectorStoreKnowledgeBaseLinkRequest",
        "VectorStoreKnowledgeBaseRef",
        "VectorStoreListResponse",
        "VectorStoreSearchHit",
        "VectorStoreSearchRequest",
        "VectorStoreSearchResponse",
        "VectorStoreState",
        "VolumeOSInitCompleteRequest",
        "VolumeOSInitGuide",
        "VolumeSnapshotListResponse",
        "VolumeSnapshotRecord",
        "WorkloadIdentityBinding",
        "WriteSandboxFileRequest"
    ));
    public static final List<String> IDEMPOTENCY_OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "createStorageBucket",
        "setStorageBucketACL",
        "createStorageBucketLifecycleRule",
        "setStorageBucketLifecycleRules",
        "uploadBucketObject",
        "createBucketPrefix",
        "setStorageBucketClass",
        "createEncryptionKey",
        "revokeEncryptionKey",
        "rotateEncryptionKey",
        "sealEncryptionObject",
        "createStorageFilesystem",
        "expandStorageFilesystem",
        "mountStorageFilesystem",
        "createFilesystemMountTarget",
        "unmountStorageFilesystem",
        "createInstance",
        "createInstanceExecSession",
        "applyInstanceLifecycle",
        "createSandboxCheckpoint",
        "cloneSandboxCheckpoint",
        "restoreSandboxCheckpoint",
        "createSandboxCodeRun",
        "writeSandboxFile",
        "createSandboxPort",
        "createSandboxToken",
        "createK8sCluster",
        "createK8sClusterNodePool",
        "updateK8sClusterNodePool",
        "proxyK8sClusterAPI",
        "upgradeK8sCluster",
        "reportTokenUsage",
        "createNetworkLoadBalancer",
        "createNetworkRoute",
        "createNetworkSecurityGroup",
        "createNetworkSecurityGroupBinding",
        "createNetworkSecurityGroupRule",
        "createNetworkSubnet",
        "createNetworkVPC",
        "createStorageObject",
        "uploadStorageObject",
        "createObservabilityAlertRule",
        "updateObservabilityAlertRule",
        "createPlatformWorkload",
        "updatePlatformWorkload",
        "applyPlatformWorkloadLifecycle",
        "createRegistryProject",
        "createRegistryProjectPullSecret",
        "setRegistryRepositoryPermission",
        "createSecret",
        "createVectorStore",
        "insertVectorStoreDocuments",
        "setVectorStoreKnowledgeBaseLink",
        "createStorageVolume",
        "setVolumeAutoSnapshotPolicy",
        "expandStorageVolume",
        "mountStorageVolume",
        "completeVolumeOSInit",
        "createVolumeSnapshot",
        "createStorageVolumeFromSnapshot",
        "unmountStorageVolume"
    ));
    public static final List<String> CURSOR_PAGINATION_OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "listStorageBuckets",
        "listBucketObjects",
        "listEncryptionKeys",
        "listStorageFilesystems",
        "listFilesystemMountTargets",
        "listGPUInventory",
        "listGPUSpecs",
        "listInstances",
        "listInstanceEvents",
        "listInstanceLogs",
        "listInstanceOperations",
        "listSandboxCheckpoints",
        "listSandboxFiles",
        "listInstanceSecurityEvents",
        "listK8sClusters",
        "listK8sClusterWorkloads",
        "listNetworkLoadBalancers",
        "listNetworkRoutes",
        "listNetworkSecurityGroups",
        "listNetworkSecurityGroupBindings",
        "listNetworkSecurityGroupRules",
        "listNetworkSubnets",
        "listNetworkSubnetIPAllocations",
        "listNetworkVPCs",
        "listStorageObjects",
        "listObservabilityAlertRules",
        "getPlatformWorkloadLogs",
        "listQuotas",
        "listRegistryImages",
        "listRegistryProjects",
        "listRegistryRepositories",
        "listRegistryArtifacts",
        "listSandboxTemplates",
        "listSecrets",
        "listVectorStores",
        "listStorageVolumes",
        "listVolumeSnapshots"
    ));
    public static final List<String> ERROR_CODES = Collections.unmodifiableList(Arrays.asList(
        "BAD_REQUEST",
        "CONFLICT",
        "DEVICE_NOT_FOUND",
        "FORBIDDEN",
        "GPU_SPEC_CONFLICT",
        "GPU_SPEC_IN_USE",
        "GPU_SPEC_NOT_FOUND",
        "GPU_TYPE_NOT_IN_NODES",
        "INTERNAL_ERROR",
        "INVALID_FILTER",
        "NOT_FOUND",
        "NOT_IMPLEMENTED",
        "PRECONDITION_FAILED",
        "QUOTA_ALREADY_EXISTS",
        "QUOTA_EXCEEDED",
        "QUOTA_NOT_FOUND",
        "QUOTA_RESOURCE_NOT_REGISTERED",
        "QUOTA_UPDATE_UNCERTAIN",
        "RATE_LIMIT_EXCEEDED",
        "RESERVATION_EXCEEDS_QUOTA",
        "RESERVED_INSUFFICIENT",
        "TENANT_NOT_FOUND",
        "UNAUTHORIZED",
        "UNAVAILABLE",
        "VALIDATION_FAILED",
        "VECTOR_STORE_NOT_FOUND"
    ));

    private final String baseUrl;
    private final String token;

    public static final class APIError {
        private final String code;
        private final String message;
        private final String requestId;
        private final Map<String, Object> details;

        public APIError(String code, String message, String requestId, Map<String, Object> details) {
            this.code = code;
            this.message = message;
            this.requestId = requestId;
            this.details = details == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(details));
        }

        public String code() {
            return code;
        }

        public String message() {
            return message;
        }

        public String requestId() {
            return requestId;
        }

        public Map<String, Object> details() {
            return details;
        }
    }

    public static final class APIException extends Exception {
        private final APIError apiError;

        public APIException(APIError apiError) {
            super(apiError == null ? "" : apiError.code() + ": " + apiError.message());
            this.apiError = apiError;
        }

        public APIError apiError() {
            return apiError;
        }
    }

    public static final class RequestOptions {
        private final String bodyJson;
        private final Map<String, String> params;
        private final Map<String, String> headers;

        public RequestOptions(String bodyJson, Map<String, String> params, Map<String, String> headers) {
            this.bodyJson = bodyJson;
            this.params = params == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(params));
            this.headers = headers == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(headers));
        }

        public String bodyJson() {
            return bodyJson;
        }

        public Map<String, String> params() {
            return params;
        }

        public Map<String, String> headers() {
            return headers;
        }
    }

    public ApiClient(String baseUrl, String token) {
        this.baseUrl = (baseUrl == null || baseUrl.isEmpty()) ? SERVER_URL : baseUrl;
        this.token = token;
    }

    public String baseUrl() {
        return baseUrl;
    }

    public String token() {
        return token;
    }

    public boolean hasOperation(String operationId) {
        return OPERATIONS.contains(operationId);
    }

    public String request(String method, String path, RequestOptions options) throws IOException, InterruptedException, APIException {
        RequestOptions opts = options == null ? new RequestOptions(null, null, null) : options;
        HttpRequest.Builder builder = HttpRequest.newBuilder(URI.create(requestUrl(path, opts.params())))
                .header("Accept", "application/json");
        if (token != null && !token.isEmpty()) {
            builder.header("Authorization", "Bearer " + token);
        }
        for (Map.Entry<String, String> entry : opts.headers().entrySet()) {
            builder.header(entry.getKey(), entry.getValue());
        }
        String upperMethod = method == null ? "GET" : method.toUpperCase();
        if (opts.bodyJson() == null) {
            builder.method(upperMethod, HttpRequest.BodyPublishers.noBody());
        } else {
            builder.header("Content-Type", "application/json");
            builder.method(upperMethod, HttpRequest.BodyPublishers.ofString(opts.bodyJson()));
        }
        HttpResponse<String> response = HTTP.send(builder.build(), HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() >= 400) {
            throw new APIException(parseAPIError(response.body(), response.statusCode()));
        }
        return response.body();
    }

    private String requestUrl(String path, Map<String, String> params) {
        String base = baseUrl.replaceAll("/+$", "");
        String relative = path == null || path.isEmpty() ? "/" : "/" + path.replaceAll("^/+", "");
        if (params == null || params.isEmpty()) {
            return base + relative;
        }
        StringJoiner query = new StringJoiner("&");
        for (Map.Entry<String, String> entry : params.entrySet()) {
            if (entry.getValue() != null && !entry.getValue().isEmpty()) {
                query.add(URLEncoder.encode(entry.getKey(), StandardCharsets.UTF_8) + "=" + URLEncoder.encode(entry.getValue(), StandardCharsets.UTF_8));
            }
        }
        String encoded = query.toString();
        return encoded.isEmpty() ? base + relative : base + relative + "?" + encoded;
    }

    private static APIError parseAPIError(String body, int statusCode) {
        String code = jsonString(body, "code");
        String message = jsonString(body, "message");
        String requestId = jsonString(body, "request_id");
        if (code == null || code.isEmpty()) {
            code = "HTTP_" + statusCode;
        }
        if (message == null || message.isEmpty()) {
            message = "ANI API request failed";
        }
        return new APIError(code, message, requestId == null ? "" : requestId, null);
    }

    private static String jsonString(String body, String field) {
        if (body == null) {
            return "";
        }
        Pattern pattern = Pattern.compile("\\\"" + Pattern.quote(field) + "\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"");
        Matcher matcher = pattern.matcher(body);
        return matcher.find() ? matcher.group(1) : "";
    }

    public static String newIdempotencyKey(String prefix) {
        String safePrefix = (prefix == null || prefix.isEmpty()) ? "ani" : prefix;
        byte[] random = new byte[16];
        RANDOM.nextBytes(random);
        StringBuilder encoded = new StringBuilder(random.length * 2);
        for (byte value : random) {
            encoded.append(String.format("%02x", value & 0xff));
        }
        return safePrefix + "_" + encoded;
    }

    public static Map<String, Object> withIdempotencyKey(Map<String, Object> body, String key) {
        Map<String, Object> payload = new HashMap<>();
        if (body != null) {
            payload.putAll(body);
        }
        payload.put("idempotency_key", (key == null || key.isEmpty()) ? newIdempotencyKey("ani") : key);
        return payload;
    }

    public static Map<String, String> cursorParams(int limit, String cursor) {
        Map<String, String> params = new HashMap<>();
        if (limit > 0) {
            params.put("limit", Integer.toString(limit));
        }
        if (cursor != null && !cursor.isEmpty()) {
            params.put("cursor", cursor);
        }
        return params;
    }

    public static boolean isAPIErrorCode(String code) {
        return ERROR_CODES.contains(code);
    }

    public static APIError apiError(String code, String message, String requestId, Map<String, Object> details) {
        return new APIError(code, message, requestId, details);
    }
}
